### PR TITLE
SB-1423: Authentication fails when concurrent requests to protected endpoints occur

### LINKED ISSUE #1519: Authentication fails when concurrent requests to protected endpoints occur
# Bug Description

Concurrent requests to protected endpoints fail with 401 Unauthorized.

# Steps To Reproduce

Save as `bug.sh`
```
#!/bin/sh
URL=http://localhost:48080/api/configuration/strongbox/storages

curl -s -I -u admin:password $URL | grep --color=always -z "401 Unauthorized" &
curl -s -I -u admin:password $URL | grep --color=always -z "401 Unauthorized" &
curl -s -I -u admin:password $URL | grep --color=always -z "401 Unauthorized" &
curl -s -I -u admin:password $URL | grep --color=always -z "401 Unauthorized" &
curl -s -I -u admin:password $URL | grep --color=always -z "401 Unauthorized" &
curl -s -I -u admin:password $URL | grep --color=always -z "401 Unauthorized" &
curl -s -I -u admin:password $URL | grep --color=always -z "401 Unauthorized" &
curl -s -I -u admin:password $URL | grep --color=always -z "401 Unauthorized" &
curl -s -I -u admin:password $URL | grep --color=always -z "401 Unauthorized" &
curl -s -I -u admin:password $URL | grep --color=always -z "401 Unauthorized" &

sleep 1

echo "Done."
```

Run `sh bug.sh` with a running `Strongbox` instance (i.e. from strongbox-web-core)

##  Received response upon 401

```
{"error":"Cannot UPDATE the record #64:0 because the version is not the latest. Probably you are updating an old record or it has been modified by another user (db=v419 your=v418)\r\n\tDB name=\"strongbox\"\r\n\tDB name=\"strongbox\"\r\n\tError Code=\"3\""}
```

# Expected Behavior

The authentication attempts succeed.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
 * @steve-todorov  
 * @sbespalov
 * @fuss86
 * @carlspring

### PR DESCRIPTION
**Pull request by sbespalov**
# Pull Request Description

This pull request closes #1519

# Acceptance Test

* [x] Building the code with `mvn clean install -Dintegration.tests` still works.
* [x] Running `mvn spring-boot:run` in the `strongbox-web-core` still starts up the application correctly.
* [x] Building the code and running the `strongbox-distribution` from a `zip` or `tar.gz` still works.
* [x] The tests in the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) still run properly.

# Questions

* Does this pull request break backward compatibility? 
  * [ ] Yes
  * [x] No

* Does this require an update of the documentation?
  * [ ] Yes, please see strongbox/strongbox-docs#{PR_NUMBER}
  * [x] No

* Does this pull request require other pull requests to be merged first? 
  * [X] Yes, please see:
https://github.com/strongbox/strongbox-db/pull/17

### CODE REVIEW

File: strongbox-security/strongbox-authentication-registry/src/test/java/org/carlspring/strongbox/authentication/ConfigurableProviderManagerTest.java [hunk 1]
```diff
@@ -68,6 +75,43 @@
     @PersistenceContext
     protected EntityManager entityManager;
 
+    @Test
+    @Transactional
+    public void testShouldNotAllowExternalUsersDublicate()
```
Comment (carlspring) [inline strongbox-security/strongbox-authentication-registry/src/test/java/org/carlspring/strongbox/authentication/ConfigurableProviderManagerTest.java]: Cosmetic: There's a small typo here:
```suggestion
    public void testShouldNotAllowExternalUserDuplicate() 
```

**Comment by carlspring** [comment]
Thanks, @sbespalov !
