### PR TITLE
issues/1476: Rest Assured concurrent test execution issues fixed

### LINKED ISSUE #1476: Get rid of static Rest Assured context
# Bug Description

Currently we have static Rest Assured context used within `strongbox-web-core` tests, which leads to issues related with Spring Application Context in the case of concurrent tests execution. The issue is that we have different instances of Spring Application Context within our tests and Rest Assured in turn uses this contexts while doing REST invocations. So while we have static Rest Assured context instance which replaced by every next context initialization and finally last initialized context always used.

# Steps To Reproduce

1. checkout [PR #954](https://github.com/strongbox/strongbox/pull/954)
2. execute `mvn test -T 4 -Dtest=LdapAuthenticatorConfigurationControllerTest#ldapConfigurationTestShouldFailWithInvalidConfiguration,PingControllerTest#shouldReturnPong -Psb` within `strongbox-web-core`
3.
```
08:26:09.850 26-09-2019 | ERROR | kJoinPool-1-worker-3 | s.c.c.s.l.LdapAuthenticatorConfigurationController | Failed to test LDAP configuration.
java.lang.ClassCastException: org.carlspring.strongbox.authentication.support.DisabledUserDetailsService cannot be cast to org.springframework.security.ldap.userdetails.LdapUserDetailsService
        at org.carlspring.strongbox.authentication.external.ldap.LdapAuthenticationConfigurationManager.lambda$testConfiguration$0(LdapAuthenticationConfigurationManager.java:67)
```
# Expected Behavior

```
BUILD SUCCESS
```

# Proposed Solution 
We need to make custom Rest Assured factory which instance will be related to current test execution. As an option it can be `ThreadLocal` instance.

# Useful links
* [RestAssuredTestExecutionListener](https://github.com/strongbox/strongbox/blob/master/strongbox-testing/strongbox-testing-web/src/test/java/org/carlspring/strongbox/rest/common/RestAssuredTestExecutionListener.java)

# Task Relationships

This bug:
* Relates to: [PR #954](https://github.com/strongbox/strongbox/pull/954)

### PR DESCRIPTION
**Pull request by sbespalov**
Fixes #1476

### CODE REVIEW

**Comment by carlspring** [comment]
Thanks for these fixes!

Basically, the main changes are in [org.carlspring.strongbox.rest.client.MockMvcRequestSpecificationProxyTarget](https://github.com/strongbox/strongbox/pull/1477/files#diff-42ec46ff218a291a5a3dd33503fbc568).

File: strongbox-rest-client/src/test/java/org/carlspring/strongbox/rest/client/RestAssuredArtifactClient.java [hunk 1]
```diff
@@ -127,12 +131,12 @@ public void put(InputStream is,
 
     private MockMvcRequestSpecification givenLocal()
     {
-        MockMvcRequestSpecification spec = RestAssuredMockMvc.given();
         if (userAgent != null)
         {
-            spec.header("User-Agent", userAgent);
+            return mockMvc.header("User-Agent", userAgent);
```
Comment (ptirador) [inline strongbox-rest-client/src/test/java/org/carlspring/strongbox/rest/client/RestAssuredArtifactClient.java]: Could you use `HttpHeaders.USER_AGENT` instead of the String constant?

File: strongbox-web-core/src/test/java/org/carlspring/strongbox/controllers/login/LoginControllerTest.java [hunk 2]
```diff
@@ -61,7 +63,7 @@ public void shouldReturnGeneratedToken()
         loginInput.setUsername("admin");
         loginInput.setPassword("password");
 
-        RestAssuredMockMvc.given()
+        mockMvc
                           .contentType("application/json")
                           .header("Accept", "application/json")
                           .body(loginInput)
```
Comment (ptirador) [inline strongbox-web-core/src/test/java/org/carlspring/strongbox/controllers/login/LoginControllerTest.java]: Could you reformat this to keep it together?

File: strongbox-web-core/src/test/java/org/carlspring/strongbox/controllers/login/LoginControllerTest.java [hunk 3]
```diff
@@ -82,7 +84,7 @@ public void shouldReturnInvalidCredentialsError()
         loginInput.setUsername("przemyslaw_fusik");
         loginInput.setPassword("password");
 
-        RestAssuredMockMvc.given()
+        mockMvc
                           .contentType("application/json")
                           .header("Accept", "application/json")
                           .body(loginInput)
```
Comment (ptirador) [inline strongbox-web-core/src/test/java/org/carlspring/strongbox/controllers/login/LoginControllerTest.java]: Could you reformat this to keep it together?

File: strongbox-web-core/src/test/java/org/carlspring/strongbox/controllers/login/LoginControllerTest.java [hunk 4]
```diff
@@ -108,7 +110,7 @@ public void shouldReturnInvalidCredentialsWhenUserIsDisabled()
         loginInput.setUsername("test-disabled-user-login");
         loginInput.setPassword("1234");
 
-        RestAssuredMockMvc.given()
+        mockMvc
                           .contentType("application/json")
                           .header("Accept", "application/json")
                           .body(loginInput)
```
Comment (ptirador) [inline strongbox-web-core/src/test/java/org/carlspring/strongbox/controllers/login/LoginControllerTest.java]: Same reformat here.

File: strongbox-web-core/src/test/java/org/carlspring/strongbox/controllers/login/LoginControllerTest.java [hunk 5]
```diff
@@ -137,7 +139,7 @@ public void userCacheShouldBeClearedAfterPasswordChange()
         loginInput.setUsername("admin-cache-eviction-test");
         loginInput.setPassword("password");
 
-        RestAssuredMockMvc.given()
+        mockMvc
                           .contentType("application/json")
                           .header("Accept", "application/json")
                           .body(loginInput)
```
Comment (ptirador) [inline strongbox-web-core/src/test/java/org/carlspring/strongbox/controllers/login/LoginControllerTest.java]: Same reformat here.

File: strongbox-web-core/src/test/java/org/carlspring/strongbox/controllers/login/LoginControllerTest.java [hunk 6]
```diff
@@ -162,7 +164,7 @@ public void userCacheShouldBeClearedAfterPasswordChange()
                .then()
                .statusCode(HttpStatus.OK.value());
 
-        RestAssuredMockMvc.given()
+        mockMvc
                           .contentType("application/json")
                           .header("Accept", "application/json")
                           .body(loginInput)
```
Comment (ptirador) [inline strongbox-web-core/src/test/java/org/carlspring/strongbox/controllers/login/LoginControllerTest.java]: Same reformat here.

File: strongbox-web-core/src/test/java/org/carlspring/strongbox/rest/common/MavenRestAssuredBaseTest.java [hunk 7]
```diff
@@ -80,7 +85,7 @@ protected boolean pathExists(String url)
     {
         logger.trace("[pathExists] URL -> " + url);
 
-        return given().header("user-agent", "Maven/*")
+        return mockMvc.header("user-agent", "Maven/*")
```
Comment (ptirador) [inline strongbox-web-core/src/test/java/org/carlspring/strongbox/rest/common/MavenRestAssuredBaseTest.java]: Could you use `HttpHeaders.USER_AGENT` instead of the String constant? Thanks!

File: strongbox-web-core/src/test/java/org/carlspring/strongbox/rest/common/RawRestAssuredBaseTest.java [hunk 8]
```diff
@@ -77,7 +82,7 @@ protected boolean pathExists(String url)
     {
         logger.trace("[pathExists] URL -> " + url);
 
-        return given().header("user-agent", "Raw/*")
+        return mockMvc.header("user-agent", "Raw/*")
```
Comment (ptirador) [inline strongbox-web-core/src/test/java/org/carlspring/strongbox/rest/common/RawRestAssuredBaseTest.java]: Could you use `HttpHeaders.USER_AGENT` instead of the String constant? Thanks!

File: strongbox-web-core/src/test/java/org/carlspring/strongbox/security/CustomAccessDeniedHandlerTest.java [hunk 9]
```diff
@@ -62,7 +62,7 @@ public void customAccessDeniedHandlerShouldRespondAsExpected()
     @WithMockUser(username = "unauthorizedUser")
     public void unauthorizedUserShouldReceiveExpectedUnauthorizedResponse()
     {
-        given().contentType("application/json")
+        mockMvc.contentType("application/json")
```
Comment (ptirador) [inline strongbox-web-core/src/test/java/org/carlspring/strongbox/security/CustomAccessDeniedHandlerTest.java]: Could you use `MediaType.APPLICATION_JSON_VALUE` instead of the String constant? Thanks!

File: strongbox-web-core/src/test/java/org/carlspring/strongbox/controllers/configuration/StoragesConfigurationControllerSmokeTest.java [hunk 10]
```diff
@@ -99,7 +99,7 @@ public void artifactShouldBeDeployedIntoNewRepository() throws IOException
                      .body(containsString(SUCCESSFUL_REPOSITORY_SAVE));
 
         // 3. Deploy artifact
-        given().header("user-agent", "Raw/*")
+        mockMvc.header("user-agent", "Raw/*")
```
Comment (ptirador) [inline strongbox-web-core/src/test/java/org/carlspring/strongbox/controllers/configuration/StoragesConfigurationControllerSmokeTest.java]: Could you use `HttpHeaders.USER_AGENT` instead of the String constant? Thanks!

File: strongbox-web-core/src/test/java/org/carlspring/strongbox/controllers/layout/maven/MavenIndexControllerTest.java [hunk 11]
```diff
@@ -289,7 +289,7 @@ public void shouldDownloadProxyRepositoryIndex(@MavenRepository(repositoryId = R
         String url = getContextBaseUrl() + "/storages/" + STORAGE0 + "/" + REPOSITORY_PROXY_4 +
                      "/.index/nexus-maven-repository-index.gz";
 
-        given().header(new Header("User-Agent", "Maven/*"))
+        mockMvc.header(new Header("User-Agent", "Maven/*"))
```
Comment (ptirador) [inline strongbox-web-core/src/test/java/org/carlspring/strongbox/controllers/layout/maven/MavenIndexControllerTest.java]: Could you use `HttpHeaders.USER_AGENT` instead of the String constant? Thanks!

File: strongbox-web-core/src/test/java/org/carlspring/strongbox/controllers/layout/maven/MavenIndexControllerTest.java [hunk 12]
```diff
@@ -322,7 +322,7 @@ public void shouldDownloadProxyRepositoryIndexPropertiesFile(@MavenRepository(re
         String url = getContextBaseUrl() + "/storages/" + STORAGE0 + "/" + REPOSITORY_PROXY_5 +
                      "/.index/nexus-maven-repository-index.properties";
 
-        given().header(new Header("User-Agent", "Maven/*"))
+        mockMvc.header(new Header("User-Agent", "Maven/*"))
```
Comment (ptirador) [inline strongbox-web-core/src/test/java/org/carlspring/strongbox/controllers/layout/maven/MavenIndexControllerTest.java]: Could you use `HttpHeaders.USER_AGENT` instead of the String constant? Thanks!
