### PR TITLE
Issue 1168: Replacing ResourceCloser with try-with-resources statements

### LINKED ISSUE #1168: Drop ResourceCloser and replace it with try-with-resources statements
# Task Description

We should drop `org.carlspring.strongbox.resource.ResourceCloser` and use [native SDK features]( https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html) instead.

# Tasks

The following classes are affected:
* [ ] `org.carlspring.strongbox.artifact.generator.NugetPackageGenerator`
* [ ] `org.carlspring.strongbox.services.ArtifactManagementServiceImplTest`
* [ ] `org.carlspring.strongbox.storage.metadata.MavenMetadataManager`
* [ ] `org.carlspring.strongbox.resource.ResourceCloser`
* [ ] `org.carlspring.strongbox.security.certificates.KeyStoreManager`
* [ ] `org.carlspring.strongbox.client.ArtifactResolverIntegrationTest`
* [ ] `org.carlspring.strongbox.controllers.BaseController`

# Acceptance Test

* [ ] Building the code with `mvn clean install -Dintegration.tests` still works.
* [ ] Running `mvn spring-boot:run` in the `strongbox-web-core` still starts up the application correctly.
* [ ] Building the code and running the `strongbox-distribution` from a `zip` or `tar.gz` still works.
* [ ] The tests in the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) still run properly.
# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

### PR DESCRIPTION
**Pull request by ogryniuk**
Fixes #1168 .

Replaced ResourceCloser in the concerned classes and deleted it afterwards. 

All four acceptance tests pass.

Side note: In the diff an additional class (TestCaseWithNugetPackageGeneration) appears as changed. 
I did not modify it at all, only open it once.

### CODE REVIEW

File: strongbox-client/src/test/java/org/carlspring/strongbox/client/ArtifactResolverIntegrationTest.java [hunk 1]
```diff
@@ -86,9 +85,16 @@ public MultiHttpClientConnThread(RestArtifactResolver artifactResolver,
...
-            CloseableRestResponse response = artifactResolver.get(url);
-            ResourceCloser.close(response, LOGGER);
+            try (CloseableRestResponse response = artifactResolver.get(url))
+            {
+                // Left empty because the original method had no other logic than the now-removed
+                // closure of a CloseableRestResponse
+            }
+            catch (Exception e)
+            {
+                LOGGER.error(e.getMessage(), e);
```
Comment (carlspring) [inline strongbox-client/src/test/java/org/carlspring/strongbox/client/ArtifactResolverIntegrationTest.java]: Cosmetic: Our loggers across the codebase are lowercase. Could you please change this? Thanks! :)

File: strongbox-client/src/test/java/org/carlspring/strongbox/client/ArtifactResolverIntegrationTest.java [hunk 2]
```diff
@@ -86,9 +85,16 @@ public MultiHttpClientConnThread(RestArtifactResolver artifactResolver,
...
+            }
         }
 
     }
-}
+}
```
Comment (carlspring) [inline strongbox-client/src/test/java/org/carlspring/strongbox/client/ArtifactResolverIntegrationTest.java]: All source and resource files should have an empty line at the end, to guarantee that all editors and build tools can read them properly.

File: strongbox-security/strongbox-security-api/src/main/java/org/carlspring/strongbox/security/certificates/KeyStoreManager.java [hunk 3]
```diff
@@ -279,22 +277,23 @@ public KeyStore addSslCertificates(Path path,
...
-        finally
-        {
-            proxyAuthenticator.getCredentials().remove();
-            ResourceCloser.close(proxySocket, logger);
+            try
+            {
+                handshake(ctx, proxySocket, host, port);
+                return tm.chain;
+            }
+
```
Comment (carlspring) [inline strongbox-security/strongbox-security-api/src/main/java/org/carlspring/strongbox/security/certificates/KeyStoreManager.java]: Cosmetic: Unnecessary empty line.

File: strongbox-security/strongbox-security-api/src/main/java/org/carlspring/strongbox/security/certificates/KeyStoreManager.java [hunk 4]
```diff
@@ -348,4 +344,4 @@ public void checkServerTrusted(X509Certificate[] chain,
         }
     }
 
-}
+}
```
Comment (carlspring) [inline strongbox-security/strongbox-security-api/src/main/java/org/carlspring/strongbox/security/certificates/KeyStoreManager.java]: Missing new line.

File: strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/main/java/org/carlspring/strongbox/storage/metadata/MavenMetadataManager.java [hunk 5]
```diff
@@ -108,15 +107,11 @@ public Metadata readMetadata(InputStream is)
     {
         Metadata metadata;
 
-        try
+        try (InputStream inputStream = is)
```
Comment (carlspring) [inline strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/main/java/org/carlspring/strongbox/storage/metadata/MavenMetadataManager.java]: I don't think this makes sense as it is. I believe the original stream should be defined here instead.

File: strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/services/ArtifactManagementServiceImplTest.java [hunk 6]
```diff
@@ -325,96 +311,79 @@ public void testDeploymentRedeploymentAndDeletionAgainstGroupRepository(TestInfo
...
+        File repositoryDir = getRepositoryBasedir(STORAGE0, repositoryGroupId);
 
-            RepositoryPath repositoryPath = repositoryPathResolver.resolve(STORAGE0,
-                                                                           repositoryGroupId,
-                                                                           ArtifactUtils.convertArtifactToPath(artifact));
-            mavenArtifactManagementService.validateAndStore(repositoryPath, is);
+        try (InputStream is = generateArtifactInputStream(repositoryDir.toPath().getParent().toAbsolutePath().toString(),
+                                                          repositoryGroupId,
+                                                          gavtc,
+                                                          true)){
```
Comment (carlspring) [inline strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/services/ArtifactManagementServiceImplTest.java]: Cosmetic: Braces on new lines, please! :)

File: strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/services/ArtifactManagementServiceImplTest.java [hunk 7]
```diff
@@ -325,96 +311,79 @@ public void testDeploymentRedeploymentAndDeletionAgainstGroupRepository(TestInfo
...
+            //noinspection EmptyCatchBlock
+            try
+            {
+                RepositoryPath repositoryPath = repositoryPathResolver.resolve(STORAGE0,
+                                                                               repositoryGroupId,
+                                                                               ArtifactUtils.convertArtifactToPath(artifact));
+                mavenArtifactManagementService.validateAndStore(repositoryPath, is);
 
-            fail("Failed to deny artifact operation for repository with disallowed deployments.");
```
Comment (carlspring) [inline strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/services/ArtifactManagementServiceImplTest.java]: I'm not sure I'm following the changes in the blocks below very well. Would you mind clarifying what you've changed, as it looks like you've changed/reformatted everything...?

File: strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/test/java/org/carlspring/strongbox/testing/TestCaseWithNugetPackageGeneration.java [hunk 8]
```diff
@@ -128,4 +128,4 @@ private String getNugetSnapshotVersion(String version)
         return version.concat("-alpha");
     }
 
-}
+}
```
Comment (carlspring) [inline strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/test/java/org/carlspring/strongbox/testing/TestCaseWithNugetPackageGeneration.java]: No new line at end of file.

File: strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/BaseController.java [hunk 9]
```diff
@@ -260,15 +259,14 @@ protected void copyToResponse(InputStream is,
                                   HttpServletResponse response)
             throws IOException
     {
-        OutputStream os = response.getOutputStream();
-
-        try
+        try (InputStream inputStream = is;
+                OutputStream os = response.getOutputStream())
```
Comment (carlspring) [inline strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/BaseController.java]: Cosmetic: Could you please re-align this line? Thanks! :)

File: strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/BaseController.java [hunk 10]
```diff
@@ -280,11 +278,6 @@ protected void copyToResponse(InputStream is,
...
         }
-        finally
-        {
-            ResourceCloser.close(is, logger);
-            ResourceCloser.close(os, logger);
-        }
     }
 
-}
+}
```
Comment (carlspring) [inline strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/BaseController.java]: No new line at the end of the file.

File: strongbox-client/src/test/java/org/carlspring/strongbox/client/ArtifactResolverIntegrationTest.java (hunk 1 above)
Comment (ogryniuk) [reply strongbox-client/src/test/java/org/carlspring/strongbox/client/ArtifactResolverIntegrationTest.java]: Hi there @carlspring , 
Thanks for all the comments, I will change the code

File: strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/main/java/org/carlspring/strongbox/storage/metadata/MavenMetadataManager.java (hunk 5 above)
Comment (ogryniuk) [reply strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/main/java/org/carlspring/strongbox/storage/metadata/MavenMetadataManager.java]: By original stream you mean to directly use the method's parameter `is`- from `readMetadata(InputStream is)`?

To close a resource, try-with-resources requires this resource to be created inside of try-with-resources parenthesis.
That is because of this that I declared a new inputstream variable in try `(InputStream inputStream = is)`.
Passing existing resources varibles directly into try-with-resources is supported from Java 9 on.
Since strongbox now uses Java 8, using original stream is not possible in current configuration.

File: strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/services/ArtifactManagementServiceImplTest.java (hunk 7 above)
Comment (ogryniuk) [reply strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/services/ArtifactManagementServiceImplTest.java]: I introduced an outer try-with-resources inside of which are put all original try statements.
This allowed to replace multiple finally blocks with one try-with-resources.

So, the essence of the change is addition of the following code:

```
try (InputStream is = generateArtifactInputStream(repositoryDir.toPath().getParent().toAbsolutePath().toString(),
                                                  repositoryGroupId,
                                                  gavtc,
                                                  true))
{ ... }
```

File: strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/main/java/org/carlspring/strongbox/storage/metadata/MavenMetadataManager.java (hunk 5 above)
Comment (carlspring) [reply strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/main/java/org/carlspring/strongbox/storage/metadata/MavenMetadataManager.java]: Oh, I didn't realize this was a method parameter.

**Comment by carlspring** [comment]
Thanks for your help, @ogryniuk! :)
