### PR TITLE
Use openjdk8 for travis-ci macOS build

### LINKED ISSUE #1956: Upgrade Travis CI to use JDK 8 >= 222
# Task Description

Since we are now enforcing JDK versions, we need to upgrade our `.travis.yml` setup so it uses a MacOS instance which has JDK 8 >= update 222 so that the build can pass.

Check [strongbox/strongbox-parent#pom.xml](https://github.com/strongbox/strongbox-parent/blob/master/pom.xml#L425)

# Task Relationships

This task:
* Relates to: #1864, #1865

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring 
  * @steve-todorov

### LINKED ISSUE #1958: MavenProxyRepositoryProviderTestIT failing test cases
# Task Description

Fix the failing test cases in MavenProxyRepositoryProviderTestIT

- whenDownloadingArtifactMetadaFileShouldAlsoBeResolved()
- whenDownloadingArtifactDatabaseShouldBeAffectedByArtifactEntry()
- whenDownloadingArtifactMetadataFileShouldBeMergedWhenExist()
- testMavenCentral()

Error logs:

```java
whenDownloadingArtifactMetadaFileShouldAlsoBeResolved()
...
java.io.IOException: Unreadable response for org/carlspring/properties-injector/1.1/properties-injector-1.1.jar. Response status is 401
at org.carlspring.strongbox.providers.repository.proxied.RemoteArtifactStreamFetcher.getConnection(RemoteArtifactStreamFetcher.java:76)

---

whenDownloadingArtifactDatabaseShouldBeAffectedByArtifactEntry()

java.io.IOException: Unreadable response for org/carlspring/properties-injector/1.6/properties-injector-1.6.jar. Response status is 401
at org.carlspring.strongbox.providers.repository.proxied.RemoteArtifactStreamFetcher.getConnection(RemoteArtifactStreamFetcher.java:76)

---

whenDownloadingArtifactMetadataFileShouldBeMergedWhenExist()
...
java.io.IOException: Unreadable response for javax/interceptor/javax.interceptor-api/1.2.2/javax.interceptor-api-1.2.2.jar. Response status is 401
at org.carlspring.strongbox.providers.repository.proxied.RemoteArtifactStreamFetcher.getConnection(RemoteArtifactStreamFetcher.java:76)

---

testMavenCentral()
...
java.io.IOException: Unreadable response for org/carlspring/maven/derby-maven-plugin/maven-metadata.xml. Response status is 401
at org.carlspring.strongbox.providers.repository.proxied.RemoteArtifactStreamFetcher.getConnection(RemoteArtifactStreamFetcher.java:76)
```

# Other info

[Travis build log](https://travis-ci.org/github/j4ckofalltrades/strongbox/builds/743618927)

JDK version:
```
$ java -version
openjdk version "1.8.0_275"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_275-b01)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.275-b01, mixed mode)
```

# Task Relationships

This task:
* Relates to: #1956 

# Useful Links

* [Related Travis-CI build](https://travis-ci.org/github/j4ckofalltrades/strongbox)

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

### PR DESCRIPTION
**Pull request by j4ckofalltrades**
@steve-todorov 

I've fixed the failing integration tests in #1958 by replacing the remote url from `repo.spring.io` to `jcenter.bintray.com` as recommended by @carlspring.

Travis CI build: https://travis-ci.org/github/j4ckofalltrades/strongbox/jobs/743752372

# Pull Request Description

This pull request closes #1956
This pull request also closes #1958

# Acceptance Test

* [x] Building the code with `mvn clean install -Dintegration.tests` still works.
* [ ] Running `mvn spring-boot:run` in the `strongbox-web-core` still starts up the application correctly.
* [ ] Building the code and running the `strongbox-distribution` from a `zip` or `tar.gz` still works.
* [ ] The tests in the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) still run properly.

# Questions

* Does this pull request break backward compatibility? 
  * [ ] Yes
  * [x] No

* Does this pull request require other pull requests to be merged first? 
  * [ ] Yes, please see #...
  * [x] No

* Does this require an update of the documentation?
  * [ ] Yes, please see strongbox/strongbox-docs#{PR_NUMBER}
  * [x] No

# Code Review And Pre-Merge Checklist

* [x] My code follows the [coding convention](https://strongbox.github.io/developer-guide/coding-convention.html) of this project.
* [x] I have performed a self-review of my own code.
* [ ] I have commented my code in hard-to-understand areas.
* [x] My changes generate no new warnings.
* [ ] I have added tests that prove my fix is effective or that my feature works.
* [x] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Review by carlspring — APPROVED** [review]
LGTM! Thanks for these fixes! :)

**Comment by carlspring** [comment]
@j4ckofalltrades ,

The build seems to still be failing under Travis. Would you mind having another look? Thanks! :)

File: strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/providers/repository/MavenProxyRepositoryProviderTestIT.java [hunk 1]
```diff
@@ -46,7 +46,8 @@
 
     private static final String REPOSITORY_ID = "spring-libs-release-it";
 
-    private static final String REMOTE_URL = "https://repo.spring.io/libs-release/";
+    // using jcenter as repositories at https://repo.spring.io now expect you to be logged in to access artifacts
```
Comment (steve-todorov) [inline strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/providers/repository/MavenProxyRepositoryProviderTestIT.java:49]: Thanks for adding this clarification comment! :)

**Review by steve-todorov — APPROVED** [review]
LGTM! Thanks for spending the time to fix this!
