### PR TITLE
Issue-1368: Added classes to handle checked exceptions

### LINKED ISSUE #1368: Handle Checked Exceptions With Lambda Expression
# Task Description

We should introduce helper classes/methods like [here](https://dzone.com/articles/how-to-handle-checked-exception-in-lambda-expressi) to help us deal with limitations of lambda expressions and checked exceptions. We should at least create 2 classes/methods:

* [ ] `ThrowingFunction.unchecked`
* [ ] `ThrowingConsumer.unchecked`
* [ ] `ThrowingSupplier.unchecked`

and try to get rid of `UndeclaredThrowableException` and `RuntimeException` calls wherever possible, as long as it does not make a code less transparent and clear.

Example of valid usage: consider [this part of code](https://github.com/strongbox/strongbox/blob/master/strongbox-data-service/src/main/java/com/orientechnologies/orient/object/jpa/OJPAObjectDatabaseTxEntityManagerFactory.java#L69). It could be rewritten like this

```
Connection connection = ThrowingSupplier.unchecked(dataSource::getConnection)
                                        .get();
```

We can do similar refactoring in the follow up tasks. We can also try to find loops in the source code, that were not able to use lambdas before, but will be using proposed classes/methods.

# Acceptance Test

* [ ] Building the code and running `mvn spring-boot:run` in the `strongbox-web-core` still starts up the application correctly.
* [ ] Building the code and running the `strongbox-distribution` from a `zip` or `tar.gz` still works.
* [ ] Running the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) still run properly.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

### PR DESCRIPTION
**Pull request by adavid9**
Fixes #1368 

Hi, I have a question is this correct way how it's implemented? I am not sure if those interfaces are correct what I mean there was mentioned that we should remove Undeclared exceptions in hand with Runtime exceptions but I am not sure if I should create similar methods that will throw different exceptions in that case Undeclared because now it throws Runtime exception. Also what about implementation of that? I've modified some code to use it, and not sure if I did it correctly. Sometimes I could not to implement it in few places as there was a pop up message that not static methods could not be implemented. I will be grateful if someone could give me some tips if those methods are correctly written or I missed something, also where in the code it should be also implemented.

@carlspring @steve-todorov @fuss86

### CODE REVIEW

File: strongbox-storage/strongbox-storage-api/src/test/java/org/carlspring/strongbox/testing/artifact/TestArtifactContext.java [hunk 1]
```diff
@@ -275,16 +264,8 @@ private void close(Path path)
...
-                try
-                {
-                    Files.delete(p);
-                }
-                catch (IOException e)
-                {
-                    throw new UndeclaredThrowableException(e);
-                }
-            });
+            s.filter(p -> !Files.isDirectory(p)).map(ThrowingFunction.unchecked(p -> p))
```
Comment (fuss86) [inline strongbox-storage/strongbox-storage-api/src/test/java/org/carlspring/strongbox/testing/artifact/TestArtifactContext.java]: `.map(ThrowingFunction.unchecked(p -> p))` unnecessary

File: strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/main/java/org/carlspring/strongbox/providers/io/MavenMetadataExpiredRepositoryPathHandler.java [hunk 2]
```diff
@@ -35,16 +35,10 @@ public boolean supports(final RepositoryPath repositoryPath)
...
         }
-        try
-        {
-            if (!RepositoryFiles.isMetadata(repositoryPath))
-            {
-                return false;
-            }
-        }
-        catch (IOException e)
+        boolean isNotMetadata = ThrowingFunction.unchecked(RepositoryFiles::isMetadata).apply(repositoryPath);
```
Comment (fuss86) [inline strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/main/java/org/carlspring/strongbox/providers/io/MavenMetadataExpiredRepositoryPathHandler.java]: ` boolean isNotMetadata` actually it returns `isMetadata`

File: strongbox-commons/src/main/java/org/carlspring/strongbox/util/ClassLoaderFactory.java [hunk 3]
```diff
@@ -29,18 +27,11 @@ public static URLClassLoader urlClassLoaderFromPaths(ClassLoader parent,
...
-            urls = new URL[uris.length];
-            for (int i = 0; i < uris.length; i++)
-            {
-                urls[i] = uris[i].toURL();
-            }
-        }
-        catch (IOException e)
+        final URI[] uris = paths.stream().map(Path::toUri).toArray(URI[]::new);
+        urls = new URL[uris.length];
+        for (int i = 0; i < uris.length; i++)
```
Comment (fuss86) [inline strongbox-commons/src/main/java/org/carlspring/strongbox/util/ClassLoaderFactory.java]: we could loop above in the stream without `.toArray(URI[]::new);`

**Comment by fuss86** [comment]
Thanks @adavid9, it looks nice :) Just couple of things to fix :)

File: strongbox-commons/src/main/java/org/carlspring/strongbox/util/ClassLoaderFactory.java (hunk 3 above)
Comment (fuss86) [reply strongbox-commons/src/main/java/org/carlspring/strongbox/util/ClassLoaderFactory.java]: now it looks beautiful :)

File: strongbox-security/strongbox-user-management/src/main/java/org/carlspring/strongbox/authorization/service/impl/AuthorizationConfigServiceImpl.java [hunk 4]
```diff
@@ -85,11 +84,7 @@ public AuthorizationConfigDto getDto()
 
         try
         {
-            return SerializationUtils.clone(authorizationConfig);
-        }
-        catch (Exception e)
```
Comment (sbespalov) [inline strongbox-security/strongbox-user-management/src/main/java/org/carlspring/strongbox/authorization/service/impl/AuthorizationConfigServiceImpl.java]: seems there is no need for `catch` here at all :smiley:

File: strongbox-cron/strongbox-cron-api/src/main/java/org/carlspring/strongbox/cron/services/impl/CronTaskDataServiceImpl.java [hunk 5]
```diff
@@ -91,11 +90,7 @@ public CronTasksConfigurationDto getTasksConfigurationDto()
 
         try
         {
-            return SerializationUtils.clone(configuration);
-        }
-        catch (Exception e)
```
Comment (sbespalov) [inline strongbox-cron/strongbox-cron-api/src/main/java/org/carlspring/strongbox/cron/services/impl/CronTaskDataServiceImpl.java]: no need for catch here as below

File: strongbox-storage/strongbox-storage-api/src/main/java/org/carlspring/strongbox/providers/repository/GroupRepositoryProvider.java [hunk 6]
```diff
@@ -250,14 +251,7 @@ protected OutputStream getOutputStreamInternal(RepositoryPath repositoryPath)
...
     {
-        try
-        {
-            return RepositoryFiles.readCoordinates((RepositoryPath) p);
-        }
-        catch (IOException e)
-        {
-            throw new RuntimeException(String.format("Failed to resolve ArtifactCoordinates for [%s]", p), e);
-        }
+        return ThrowingFunction.unchecked(RepositoryFiles::readCoordinates).apply((RepositoryPath) p);
```
Comment (sbespalov) [inline strongbox-storage/strongbox-storage-api/src/main/java/org/carlspring/strongbox/providers/repository/GroupRepositoryProvider.java]: @adavid9 can you please add `throws IOException` here and use `TrowingFunction` at `GroupRepositoryProvider.search` ?

File: strongbox-storage/strongbox-storage-api/src/main/java/org/carlspring/strongbox/services/impl/ConfigurationManagementServiceImpl.java [hunk 7]
```diff
@@ -87,11 +86,7 @@ public MutableConfiguration getMutableConfigurationClone()
 
         try
         {
-            return SerializationUtils.clone(configuration);
-        }
-        catch (Exception e)
```
Comment (sbespalov) [inline strongbox-storage/strongbox-storage-api/src/main/java/org/carlspring/strongbox/services/impl/ConfigurationManagementServiceImpl.java]: don't need for `catch`

File: strongbox-storage/strongbox-storage-api/src/main/java/org/carlspring/strongbox/services/impl/RepositoryManagementServiceImpl.java [hunk 8]
```diff
@@ -243,21 +244,10 @@ public void undeleteTrash()
...
-                        RepositoryFiles.undelete(repositoryPath);
-                    }
-                }
-                catch (Exception e)
+                if (repository.isTrashEnabled())
                 {
-                    throw new RuntimeException("Unable to undelete trash for storage " + storageId + " in repository " +
-                                               repositoryId, e);
+                    RootRepositoryPath repositoryPath = repositoryPathResolver.resolve(repository);
+                    ThrowingConsumer.unchecked(RepositoryFiles::undelete).accept(repositoryPath);
```
Comment (sbespalov) [inline strongbox-storage/strongbox-storage-api/src/main/java/org/carlspring/strongbox/services/impl/RepositoryManagementServiceImpl.java]: @adavid9  can you please add `throws IOException` and replace original `catch (Exception)` with following:
```
catch (IOException e)
                {
                    throw new ArtifactStorageException("Unable to undelete trash for storage " + storageId + " in repository " +
                                               repositoryId, e);
                }
```

File: strongbox-storage/strongbox-storage-api/src/test/java/org/carlspring/strongbox/testing/artifact/TestArtifactContext.java [hunk 9]
```diff
@@ -209,31 +211,18 @@ private void store(Map.Entry<RepositoryPath, Path> e)
...
-        try
-        {
-            Files.delete(e.getValue());
-        }
-        catch (IOException ioe)
-        {
-            throw new UndeclaredThrowableException(ioe);
-        }
+
+        ThrowingConsumer.unchecked(Files::delete).accept(e.getValue());
```
Comment (sbespalov) [inline strongbox-storage/strongbox-storage-api/src/test/java/org/carlspring/strongbox/testing/artifact/TestArtifactContext.java]: @adavid9 can you please add `throws IOException` and use `ThrowingConsumer` within `TestArtifactContext.deployArtifact()` foreach

File: strongbox-storage/strongbox-storage-api/src/test/java/org/carlspring/strongbox/testing/artifact/TestArtifactContext.java [hunk 10]
```diff
@@ -209,31 +211,18 @@ private void store(Map.Entry<RepositoryPath, Path> e)
...
                                                  RepositoryPath p2)
     {
         Boolean isChecksumP1;
         Boolean isChecksumP2;
-        try
-        {
-            isChecksumP1 = RepositoryFiles.isChecksum(p1);
-            isChecksumP2 = RepositoryFiles.isChecksum(p2);
-        }
-        catch (IOException e)
```
Comment (sbespalov) [inline strongbox-storage/strongbox-storage-api/src/test/java/org/carlspring/strongbox/testing/artifact/TestArtifactContext.java]: we better add `throws IOException` here with `TrwoingComparator` interface within `deployArtifact` method

File: strongbox-storage/strongbox-storage-api/src/test/java/org/carlspring/strongbox/testing/storage/repository/TestRepositoryContext.java [hunk 11]
```diff
@@ -217,14 +218,8 @@ private Storage createStorage()
...
-        try
-        {
-            storageManagementService.saveStorage(newStorage);
-        }
-        catch (IOException e)
-        {
-            throw new UndeclaredThrowableException(e);
-        }
+
+        ThrowingConsumer.unchecked(storageManagementService::saveStorage).accept(newStorage);
```
Comment (sbespalov) [inline strongbox-storage/strongbox-storage-api/src/test/java/org/carlspring/strongbox/testing/storage/repository/TestRepositoryContext.java]: same as above, we should add `throws IOException` here and use `ThrowingSupplier` where this method used

File: strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/main/java/org/carlspring/strongbox/providers/io/MavenMetadataExpiredRepositoryPathHandler.java [hunk 12]
```diff
@@ -35,16 +35,10 @@ public boolean supports(final RepositoryPath repositoryPath)
...
         }
-        try
-        {
-            if (!RepositoryFiles.isMetadata(repositoryPath))
-            {
-                return false;
-            }
-        }
-        catch (IOException e)
+        boolean isMetadata = ThrowingFunction.unchecked(RepositoryFiles::isMetadata).apply(repositoryPath);
```
Comment (sbespalov) [inline strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/main/java/org/carlspring/strongbox/providers/io/MavenMetadataExpiredRepositoryPathHandler.java]: I think we can add `throws IOException` for `ExpiredRepositoryPathHandler.supports` method and use `ThrowingPredicate` where this method used

File: strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-npm-layout-provider/src/test/java/org/carlspring/strongbox/artifact/generator/NpmArtifactGenerator.java [hunk 13]
```diff
@@ -112,14 +110,7 @@ private void calculateChecksum()
         throws IOException
     {
         MessageDigest crypt;
-        try
-        {
-            crypt = MessageDigest.getInstance("SHA-1");
-        }
-        catch (NoSuchAlgorithmException e)
-        {
-            throw new UndeclaredThrowableException(e);
```
Comment (sbespalov) [inline strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-npm-layout-provider/src/test/java/org/carlspring/strongbox/artifact/generator/NpmArtifactGenerator.java]: we can replace it with `throw new IOException(e)` instead of using `ThrowingFunction`

**Comment by adavid9** [comment]
@sbespalov Thanks for the CR. I will take a look at that today, I missed some things and thanks for advices how to improve others.

File: strongbox-storage/strongbox-storage-api/src/main/java/org/carlspring/strongbox/providers/repository/GroupRepositoryProvider.java (hunk 6 above)
Comment (adavid9) [reply strongbox-storage/strongbox-storage-api/src/main/java/org/carlspring/strongbox/providers/repository/GroupRepositoryProvider.java]: @sbespalov To ensure that I understand it correctly, I should remove `ThrowingFunction` from this place and left it as it was before, but use `ThrowingFunction` in `GroupRepositoryProvider.search`?

Comment (sbespalov) [reply strongbox-storage/strongbox-storage-api/src/main/java/org/carlspring/strongbox/providers/repository/GroupRepositoryProvider.java]: yes, but you should also throw `IOException` instead of `RuntimeException`

File: strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/main/java/org/carlspring/strongbox/providers/io/MavenMetadataExpiredRepositoryPathHandler.java (hunk 12 above)
Comment (sbespalov) [reply strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/main/java/org/carlspring/strongbox/providers/io/MavenMetadataExpiredRepositoryPathHandler.java]: @adavid9 you don't need to catch and re-throw `IOException` here, just add it to method declaration

**Comment by sbespalov** [comment]
thanks  @adavid9 

@carlspring LGTM now

**Comment by steve-todorov** [comment]
Thanks for your work on this @adavid9! :)

**Comment by fuss86** [comment]
Congrats @adavid9 and thanks !
