### PR TITLE
Issue-1840: Improve password encoding support for LDAP

### LINKED ISSUE #1840: Improve password encoding support for LDAP
# Bug Description

In LDAP the `userPassword` attribute contains the hash of the password encoded as `base64` and the end result in LDAP will be something like this `{ALG}base64.encode(md5/sha1/bcrypt(mypassword))`. The `PasswordEncoder` in Spring, however, expects that the part after `{ALG}` is actually the `hash` which causes login failures. If you have saved the `userPassword` using [PasswordEncoderFactories.createDelegatingPasswordEncoder](https://docs.spring.io/spring-security/site/docs/5.2.x/api/org/springframework/security/crypto/factory/PasswordEncoderFactories.html) it will work just fine, but in all other cases it will fail since the the compared hashed strings won't match.

# Solution

- [ ] Create a custom version of `org.springframework.security.ldap.userdetails.LdapUserDetailsMapper` which overrides the `mapPassword` with optional `base64.decode` logic 
- [ ] Use this custom version of `LdapUserDetailsMapper` for `LdapUserDetailsService` (see `strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/main/resources/org/carlspring/strongbox/authentication/external/ldap/strongbox-authentication-providers.xml`)
- [ ] ~~Also, it should be configurable with `strongbox.authentication.ldap.base64EncodedPassword=true|false`~~
- [ ] Write a unit test case for the `CustomUserDetailsMapper` to ensure it works properly with and without `base64` encoded hash as described:
    ```
  {ALG}md5/sha1/bcrypt(mypassword)
  {ALG}base64.encode(md5/sha1/bcrypt(mypassword))
  base64.encode({ALG}md5/sha1/bcrypt(mypassword))
    ```
- [ ] Write an integration test which uses Unboundid so we test against a real LDAP server. Some additional user records will need to be added in the testing `ldif` for this purpose.
org.carlspring.strongbox.config.SecurityConfig to org.carlspring.strongbox.config.WebSecurityConfig
- [ ] [SecurityConfig.java] -
   * Rename this class to `WebSecurityConfig` for better consistency with Spring naming convention.

[SecurityConfig.java]: https://github.com/strongbox/strongbox/blob/f6f280c8e01fe32b8681b5f4f9dd8c9aee9e1d2d/strongbox-web-core/src/main/java/org/carlspring/strongbox/config/SecurityConfig.java

# Useful Links

* [RFC4519#userPassword](https://tools.ietf.org/html/rfc4519#section-2.41)
* [RFC3112](https://tools.ietf.org/html/rfc3112)

# Task Relationships

This bug:
* Is follow-up of: #1670, #1614 
* Relates to: #1679 , #1846 , #1858

### PR DESCRIPTION
**Pull request by madhukarbharti**
# Pull Request Description

This pull request closes #1840

# Acceptance Test

* [x] Building the code with `mvn clean install -Dintegration.tests` still works.
* [x] Running `mvn spring-boot:run` in the `strongbox-web-core` still starts up the application correctly.
* [x] Building the code and running the `strongbox-distribution` from a `zip` or `tar.gz` still works.
* [x] The tests in the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) still run properly.

# Questions

* Does this pull request break backward compatibility? 
  * [ ] Yes
  * [x] No

* Does this pull request require other pull requests to be merged first? 
  * [ ] Yes, please see #...
  * [x] No, but should be merged together with strongbox/strongbox-web-ui#45

* Does this require an update of the documentation?
  * [ ] Yes, please see strongbox/strongbox-docs#{PR_NUMBER}
  * [x] No

# Code Review And Pre-Merge Checklist

* [x] My code follows the [coding convention](https://strongbox.github.io/developer-guide/coding-convention.html) of this project.
* [x] I have performed a self-review of my own code.
* [x] I have commented my code in hard-to-understand areas.
* [x] My changes generate no new warnings.
* [x] I have added tests that prove my fix is effective or that my feature works.
* [x] New and existing unit tests pass locally with my changes.

### CODE REVIEW

File: strongbox-security/strongbox-security-api/src/test/java/org/carlspring/strongbox/configuration/StrongboxDelegatingPasswordEncoderTest.java [hunk 1]
```diff
@@ -0,0 +1,46 @@
...
+        String text = "password12";
+        String base64EncodedString = new String(Base64.getEncoder().encode(text.getBytes()));
+
+        String normalEncode = passwordEncoder.encode(text);
+        String base64Encode = passwordEncoder.encode(base64EncodedString);
+
+        Assertions.assertTrue(passwordEncoder.matches(text, normalEncode));
+        Assertions.assertTrue(passwordEncoder.matches(text, base64Encode));
+    }
+}
```
Comment (carlspring) [inline strongbox-security/strongbox-security-api/src/test/java/org/carlspring/strongbox/configuration/StrongboxDelegatingPasswordEncoderTest.java:46]: No new line at the end of the file.

**Review by carlspring — CHANGES_REQUESTED** [review]
@madhukarbharti ,

Please, re-format your changes (only) according to our [coding convention](https://strongbox.github.io/developer-guide/coding-convention.html). Could you please also check the "Code Review And Pre-Merge Checklist", as explained in your pull request?

Thank you! :)

File: strongbox-security/strongbox-security-api/src/main/java/org/carlspring/strongbox/configuration/StrongboxDelegatingPasswordEncoder.java [hunk 2]
```diff
@@ -0,0 +1,72 @@
...
+
+/**
+ *  This class encodes given raw String or Base64 encoded string.
+ *  If given string is Base64 Encoded it will attempt to decode the password and finally delegate it to the password encoder.
+ *
+ * @author mbharti
+ * @date 07/10/20
+ */
+@Component
+public class StrongboxDelegatingPasswordEncoder implements PasswordEncoder {
```
Comment (carlspring) [inline strongbox-security/strongbox-security-api/src/main/java/org/carlspring/strongbox/configuration/StrongboxDelegatingPasswordEncoder.java:17]: Cosmetic: Braces on new lines (here and everywhere across the pull request), please. :)

File: strongbox-security/strongbox-security-api/src/test/java/org/carlspring/strongbox/configuration/StrongboxDelegatingPasswordEncoderTest.java [hunk 3]
```diff
@@ -0,0 +1,46 @@
...
+
+@SpringBootTest
+@ActiveProfiles(profiles = "test")
+@ContextConfiguration
+class StrongboxDelegatingPasswordEncoderTest {
+
+    @org.springframework.context.annotation.Configuration
+    @ComponentScan(basePackages = {"org.carlspring.strongbox.security",
+            "org.carlspring.strongbox.testing", "org.carlspring.strongbox.configuration"})
+    public static class SpringConfig {
```
Comment (carlspring) [inline strongbox-security/strongbox-security-api/src/test/java/org/carlspring/strongbox/configuration/StrongboxDelegatingPasswordEncoderTest.java:22]:
```suggestion
    @ComponentScan(basePackages = { "org.carlspring.strongbox.security",
                                    "org.carlspring.strongbox.testing",
                                    "org.carlspring.strongbox.configuration" })
    public static class SpringConfig
    {
```

File: strongbox-security/strongbox-security-api/src/main/java/org/carlspring/strongbox/configuration/StrongboxDelegatingPasswordEncoder.java (hunk 2 above)
Comment (madhukarbharti) [reply strongbox-security/strongbox-security-api/src/main/java/org/carlspring/strongbox/configuration/StrongboxDelegatingPasswordEncoder.java:17]: @carlspring Sorry! will format according to our coding convention

File: strongbox-security/strongbox-security-api/src/main/java/org/carlspring/strongbox/configuration/StrongboxDelegatingPasswordEncoder.java [hunk 4]
```diff
@@ -0,0 +1,72 @@
+package org.carlspring.strongbox.configuration;
+
+import com.hazelcast.util.Base64;
```
Comment (carlspring) [inline strongbox-security/strongbox-security-api/src/main/java/org/carlspring/strongbox/configuration/StrongboxDelegatingPasswordEncoder.java:3]: Why this import? Isn't the standard class from the Java SDK good enough?

Comment (madhukarbharti) [reply strongbox-security/strongbox-security-api/src/main/java/org/carlspring/strongbox/configuration/StrongboxDelegatingPasswordEncoder.java:3]: Java SDK Base64 doesn't have an API to check if a given string is already encoded in Base64. But yeah we can go without this library. I will use SDK Base64

Comment (carlspring) [reply strongbox-security/strongbox-security-api/src/main/java/org/carlspring/strongbox/configuration/StrongboxDelegatingPasswordEncoder.java:3]: I'm sure Spring must have something useful in this regard. My concern is that Hazelcast is a library for caching and, perhaps, some day, we might think of replacing it with some other solution and then this code would have to be revisited. In this particular case, I don't think that this is the correct import, so I would advise you to look for something better.

File: strongbox-security/strongbox-security-api/src/main/java/org/carlspring/strongbox/configuration/StrongboxDelegatingPasswordEncoder.java [hunk 5]
```diff
@@ -0,0 +1,80 @@
...
+        String base64EncodedString = Base64Utils.encodeToString(base64DecodedString.getBytes());
+
+        if (rawString.equals(base64EncodedString))
+        {
+            return base64DecodedString;
+        }
+
+        return rawString;
+    }
+}
```
Comment (carlspring) [inline strongbox-security/strongbox-security-api/src/main/java/org/carlspring/strongbox/configuration/StrongboxDelegatingPasswordEncoder.java:80]: Cosmetic: Please, add a new line at the end of this file.

File: strongbox-security/strongbox-security-api/src/main/java/org/carlspring/strongbox/configuration/StrongboxDelegatingPasswordEncoder.java [hunk 6]
```diff
@@ -0,0 +1,88 @@
...
+     * false if the password do not match
+     */
+    @Override
+    public boolean matches(CharSequence rawCharSequence,
+                           String encodedString)
+    {
+        return passwordEncoder.matches(getDecodedString(rawCharSequence), encodedString);
+    }
+
+    private String getDecodedString(CharSequence rawCharSequence)
```
Comment (steve-todorov) [inline strongbox-security/strongbox-security-api/src/main/java/org/carlspring/strongbox/configuration/StrongboxDelegatingPasswordEncoder.java:60]: The implementation of this method is incorrect. You need to **remove** the `{alg}` part **before** decoding the string, because otherwise it will fail to decode. Check the issue description again: #1840.

File: strongbox-security/strongbox-security-api/src/test/java/org/carlspring/strongbox/configuration/StrongboxDelegatingPasswordEncoderTest.java [hunk 7]
```diff
@@ -0,0 +1,53 @@
...
+
+    @Test
+    void testNullEncodeAndMatch()
+    {
+        Assertions.assertThrows(NullPointerException.class, () -> passwordEncoder.encode(null));
+        Assertions.assertTrue(passwordEncoder.matches(null, null));
+    }
+
+    @Test
+    void encodeAndMatch()
```
Comment (steve-todorov) [inline strongbox-security/strongbox-security-api/src/test/java/org/carlspring/strongbox/configuration/StrongboxDelegatingPasswordEncoderTest.java:42]: This test case is not properly testing the real scenario. Check #1840 (specifically the `{alg}` part).
If it is supposed to test a raw password which is not hashed and has no hash algorithm - the method should probably be renamed to something like `rawNoAlgPasswordShouldEncode()`. 
Naming is important as it gives context to what this test is all about!

File: strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/test/java/org/carlspring/strongbox/authentication/api/impl/ldap/LdapAuthenticationProviderTest.java [hunk 8]
```diff
@@ -83,6 +83,24 @@ public void embeddedLdapServerRegistersExpectedAuthenticationProvider()
...
+        LdapUserDetails ldapUserDetails = (LdapUserDetailsImpl) ldapUser;
+
+        assertThat(ldapUserDetails.getDn()).isEqualTo("uid=base64encoded-issue-1840,ou=Users,dc=carlspring,dc=com");
+        assertThat(ldapUserDetails.getPassword()).isEqualTo("{bcrypt}JDJhJDEwJGxwd2x4eWp2WEt6TjFjY0NydzJQQnVaeC5lVmVzV2JmbVRic3JDYm9NVS5nc05XVmNaV01p");
+        assertThat(ldapUserDetails.getUsername()).isEqualTo("base64encoded-issue-1840");
+        assertThat(((List<SimpleGrantedAuthority>)ldapUser.getAuthorities()))
+                .contains(
+                        new SimpleGrantedAuthority(SystemRole.REPOSITORY_MANAGER.name()),
+                        new SimpleGrantedAuthority("USER_ROLE")
+                );
```
Comment (steve-todorov) [inline strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/test/java/org/carlspring/strongbox/authentication/api/impl/ldap/LdapAuthenticationProviderTest.java:101]: This test actually doesn't do anything other than validating it can get a record from the LDAP server. :)
It should also have an assertion which checks if `passwordEncoder.matches(ldapUserDetails.getPassword(), "password")`.

File: strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/test/resources/strongbox.ldif [hunk 9]
```diff
@@ -24,6 +24,19 @@ givenName: Martin
...
+objectClass: inetOrgPerson
+objectClass: organizationalPerson
+objectClass: person
+objectClass: top
+uid: base64encoded-issue-1840
+cn: base64encoded-issue-1840
+mail: mtodorov@carlspring.com
+givenName: Martin
+surname: Todorov
+userPassword: {bcrypt}JDJhJDEwJGxwd2x4eWp2WEt6TjFjY0NydzJQQnVaeC5lVmVzV2JmbVRic3JDYm9NVS5nc05XVmNaV01p
```
Comment (steve-todorov) [inline strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/test/resources/strongbox.ldif:38]: Could you please change this to:
```suggestion
userPassword: {MD5}X03MO1qnZdYdgyfeuILPmQ==
```
I'm sorry - I noticed this after our chat.  
OpenLDAP doesn't support `bcrypt` logins and for this specific case `MD5` is easier to debug via ApacheDS Studio. :)

File: strongbox-security/strongbox-security-api/src/main/java/org/carlspring/strongbox/configuration/StrongboxDelegatingPasswordEncoder.java [hunk 10]
```diff
@@ -0,0 +1,88 @@
...
+        implements PasswordEncoder
+{
+
+    private PasswordEncoder passwordEncoder;
+
+    @PostConstruct
+    private void init()
+    {
+        passwordEncoder = PasswordEncoderFactories.createDelegatingPasswordEncoder();
+    }
```
Comment (steve-todorov) [inline strongbox-security/strongbox-security-api/src/main/java/org/carlspring/strongbox/configuration/StrongboxDelegatingPasswordEncoder.java:28]: I think this should be a constructor - there's no point in having a `@PosConstruct`. It will also produce a `NPE` when you try to instantiate via `new StrongboxDelegatingPasswordEncoder()` because the `private PasswordEncoder passwordEncoder` will be null.

**Review by steve-todorov — CHANGES_REQUESTED** [review]

File: strongbox-security/strongbox-security-api/src/main/java/org/carlspring/strongbox/configuration/StrongboxDelegatingPasswordEncoder.java [hunk 11]
```diff
@@ -0,0 +1,130 @@
...
+            if (StringUtils.isNotEmpty(algorithmUsed))
+            {
+                encodedPassword = extractEncodedPassword(prefixEncodedPasswordString);
+            }
+
+            return PREFIX + algorithmUsed + SUFFIX +
+                   new String(Hex.encode(Base64.getDecoder().decode(Utf8.encode(encodedPassword))));
+        }
+        catch (Exception ex)
+        {
```
Comment (sbespalov) [inline strongbox-security/strongbox-security-api/src/main/java/org/carlspring/strongbox/configuration/StrongboxDelegatingPasswordEncoder.java:100]: will be better to have some `WARN` logs here.

File: strongbox-security/strongbox-security-api/src/main/java/org/carlspring/strongbox/configuration/StrongboxDelegatingPasswordEncoder.java [hunk 12]
```diff
@@ -0,0 +1,130 @@
...
+
+/**
+ * This class encodes given raw String or Base64 encoded string.
+ * If given string is Base64 Encoded it will attempt to decode the password and finally delegate it to the password encoder.
+ *
+ * @author mbharti
+ * @date 07/10/20
+ */
+@Component
+public class StrongboxDelegatingPasswordEncoder
```
Comment (sbespalov) [inline strongbox-security/strongbox-security-api/src/main/java/org/carlspring/strongbox/configuration/StrongboxDelegatingPasswordEncoder.java:20]: better name will be `Base64DelegatingPasswordEncoder`

File: strongbox-security/strongbox-security-api/src/main/java/org/carlspring/strongbox/configuration/StrongboxDelegatingPasswordEncoder.java [hunk 13]
```diff
@@ -0,0 +1,130 @@
...
+        try
+        {
+            String encodedPassword = prefixEncodedPasswordString;
+
+            if (StringUtils.isNotEmpty(algorithmUsed))
+            {
+                encodedPassword = extractEncodedPassword(prefixEncodedPasswordString);
+            }
+
+            return PREFIX + algorithmUsed + SUFFIX +
```
Comment (sbespalov) [inline strongbox-security/strongbox-security-api/src/main/java/org/carlspring/strongbox/configuration/StrongboxDelegatingPasswordEncoder.java:96]: if there is no `algorithmUsed` value then we don't need `PREFIX` and `SUFFIX`.

File: strongbox-security/strongbox-security-api/src/main/java/org/carlspring/strongbox/configuration/StrongboxDelegatingPasswordEncoder.java [hunk 14]
```diff
@@ -0,0 +1,130 @@
...
+@Component
+public class StrongboxDelegatingPasswordEncoder
+        implements PasswordEncoder
+{
+
+    private static final String PREFIX = "{";
+
+    private static final String SUFFIX = "}";
+
+    private PasswordEncoder passwordEncoder;
```
Comment (sbespalov) [inline strongbox-security/strongbox-security-api/src/main/java/org/carlspring/strongbox/configuration/StrongboxDelegatingPasswordEncoder.java:28]: `private final PasswordEncoder passwordEncoder;`

File: strongbox-security/strongbox-security-api/src/main/java/org/carlspring/strongbox/configuration/StrongboxDelegatingPasswordEncoder.java [hunk 15]
```diff
@@ -0,0 +1,130 @@
...
+
+
+    public StrongboxDelegatingPasswordEncoder()
+    {
+        passwordEncoder = PasswordEncoderFactories.createDelegatingPasswordEncoder();
```
Comment (sbespalov) [inline strongbox-security/strongbox-security-api/src/main/java/org/carlspring/strongbox/configuration/StrongboxDelegatingPasswordEncoder.java:33]: better will be to have `passwordEncoder` as constructor argument.

**Review by sbespalov — COMMENTED** [review]
@madhukarbharti thanks for the PR, it looks very good! Just few minor comments, please proceed with it so we could merge.

File: strongbox-security/strongbox-security-api/src/main/java/org/carlspring/strongbox/configuration/Base64PasswordEncoderDelegate.java [hunk 16]
```diff
@@ -0,0 +1,207 @@
...
+import org.springframework.stereotype.Component;
+
+/**
+ * This class encodes given raw String or Base64 encoded string.
+ * If given string is Base64 Encoded it will attempt to decode the password and finally delegate it to the password encoder.
+ * This handles all possible cases
+ * <p>
+ * {ALG}md5/sha1/bcrypt(mypassword)
+ * {ALG}base64.encode(md5/sha1/bcrypt(mypassword))
+ * base64.encode({ALG}md5/sha1/bcrypt(mypassword))
```
Comment (sbespalov) [inline strongbox-security/strongbox-security-api/src/main/java/org/carlspring/strongbox/configuration/Base64PasswordEncoderDelegate.java:20]: :+1:

File: strongbox-security/strongbox-security-api/src/main/java/org/carlspring/strongbox/configuration/Base64PasswordEncoderDelegate.java [hunk 17]
```diff
@@ -0,0 +1,207 @@
...
+     * This Encodes the raw password. In case given rawCharSequence is Base64 encoded,
+     * then it will decode and then encode the decoded string.
+     *
+     * @param rawCharSequence Raw String or Base64 encoded String
+     * @return Encoded String
+     */
+    @Override
+    public String encode(CharSequence rawCharSequence)
+    {
+        return passwordEncoder.encode(rawCharSequence);
```
Comment (sbespalov) [inline strongbox-security/strongbox-security-api/src/main/java/org/carlspring/strongbox/configuration/Base64PasswordEncoderDelegate.java:59]: maybe we should do Base 64 encode here as well?

File: strongbox-security/strongbox-security-api/src/test/java/org/carlspring/strongbox/configuration/Base64PasswordEncoderDelegateTest.java [hunk 18]
```diff
@@ -0,0 +1,71 @@
...
+
+import org.junit.jupiter.api.Assertions;
+import org.junit.jupiter.api.Test;
+import org.springframework.boot.test.context.SpringBootTest;
+import org.springframework.context.annotation.ComponentScan;
+import org.springframework.security.crypto.password.PasswordEncoder;
+import org.springframework.test.context.ActiveProfiles;
+import org.springframework.test.context.ContextConfiguration;
+
+@SpringBootTest
```
Comment (sbespalov) [inline strongbox-security/strongbox-security-api/src/test/java/org/carlspring/strongbox/configuration/Base64PasswordEncoderDelegateTest.java:13]: it's seems that we don't need any Spring context here, you can just directly create `Base64PasswordEncoderDelegate` instance to test.

File: strongbox-security/strongbox-security-api/src/main/java/org/carlspring/strongbox/configuration/WebSecurityConfig.java [hunk 19]
```diff
@@ -12,14 +12,14 @@
 @ComponentScan({ "org.carlspring.strongbox.configuration",
                  "org.carlspring.strongbox.security",
                  "org.carlspring.strongbox.visitors" })
-public class StrongboxSecurityConfig
+public class WebSecurityConfig
```
Comment (sbespalov) [inline strongbox-security/strongbox-security-api/src/main/java/org/carlspring/strongbox/configuration/WebSecurityConfig.java:15]: seems we have some confusion with this naming refactoring, details [here](https://github.com/strongbox/strongbox/issues/1840#issuecomment-709946439)

File: strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/test/java/org/carlspring/strongbox/authentication/api/impl/ldap/LdapAuthenticationProviderTest.java [hunk 20]
```diff
@@ -43,11 +45,18 @@
 public class LdapAuthenticationProviderTest
 {
 
+    @org.springframework.context.annotation.Configuration
+    @ComponentScan(basePackages = { "org.carlspring.strongbox.configuration"})
+    public static class SpringConfig { }
```
Comment (sbespalov) [inline strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/test/java/org/carlspring/strongbox/authentication/api/impl/ldap/LdapAuthenticationProviderTest.java:50]: it will be better to expectedly add `StrongboxSecurityConfig` to `@ContextHierarchy` of this test class.

**Review by sbespalov — CHANGES_REQUESTED** [review]
@madhukarbharti thanks for the changes. There is few more comments, could you please proceed with it as well?

File: strongbox-security/strongbox-security-api/src/main/java/org/carlspring/strongbox/configuration/Base64PasswordEncoderDelegate.java (hunk 17 above)
Comment (madhukarbharti) [reply strongbox-security/strongbox-security-api/src/main/java/org/carlspring/strongbox/configuration/Base64PasswordEncoderDelegate.java:59]: if we do Base64Enocding here, will it get applied to all passwords encoded by the underlying framework? In that case, we will be adding extra one more level of encoding decoding?
Also while decoding we just decode with the given raw password and encoded password
if that fails then all other possible checks start.

- Currently, if a password generated by this framework, it will pass at first go itself without doing any encoding decoding. In case it fails it will try the other two possible scenarios 


Please share your thoughts on this, we can change it accordingly

Comment (sbespalov) [reply strongbox-security/strongbox-security-api/src/main/java/org/carlspring/strongbox/configuration/Base64PasswordEncoderDelegate.java:59]: thanks for clarifying!
I seems missed that this is just common `PasswordEncoder` that we use for all purposes. Considering that it would be good to apply this base 64 related logic only for LDAP and this seems not possible with `PasswordEncoder` in our case. So I'm just noticed that we could customize `LdapUserDetailsMapper.mapPassword` for this purpose. 
@madhukarbharti,  could you please try to proceed this way? The suggestion is to have customized `LdapUserDetailsMapper` implementation with optional base 64 decode logic. This could be configurable in `/strongbox-ldap-authentication-provider/src/main/resources/org/carlspring/strongbox/authentication/external/ldap/strongbox-authentication-providers.xml` with `strongbox.authentication.ldap.base64EncodedPassword=true|false` property.

File: strongbox-security/strongbox-security-api/src/main/java/org/carlspring/strongbox/configuration/WebSecurityConfig.java (hunk 19 above)
Comment (sbespalov) [reply strongbox-security/strongbox-security-api/src/main/java/org/carlspring/strongbox/configuration/WebSecurityConfig.java:15]: @madhukarbharti please leave `StrongboxSecurityConfig` name here and rename the `/strongbox-web-core/src/main/java/org/carlspring/strongbox/config/SecurityConfig.java` to `WebSecurityConfig` instead.

**Comment by sbespalov** [comment]
@madhukarbharti thanks for your hard working on this task! there is some new clarifications of how we could proceed with LDAP password decode, could you please have a look?

**Comment by carlspring** [comment]
Hi,

Please, be advised of the upcoming changes by @mknutsen79 in strongbox/strongbox-parent#l113. You will have to rebase.

**Comment by carlspring** [comment]
@madhukarbharti , @sbespalov , @steve-todorov ,

What is the status of this task?

**Comment by madhukarbharti** [comment]
@sbespalov @steve-todorov Updated PR, Can you please find some time to review and share your review comments.

Regards,
Madhukar

File: strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/main/java/org/carlspring/strongbox/authentication/api/ldap/CustomLdapUserDetailsMapper.java [hunk 21]
```diff
@@ -0,0 +1,150 @@
+package org.carlspring.strongbox.authentication.api.ldap;
+
+import java.util.Base64;
+
+import org.apache.commons.lang3.StringUtils;
```
Comment (carlspring) [inline strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/main/java/org/carlspring/strongbox/authentication/api/ldap/CustomLdapUserDetailsMapper.java:5]: Perhaps it would be better to use Spring's implementation of the `StringUtils`. Are you using anything in particular that it doesn't support?

File: strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/main/java/org/carlspring/strongbox/authentication/api/ldap/CustomLdapUserDetailsMapper.java [hunk 22]
```diff
@@ -0,0 +1,150 @@
...
+            String base64DecodedPasswordAfterAlgorithm;
+
+            String extractBase64EncodedHash = prefixEncodedPasswordString;
+
+            if (StringUtils.isNotEmpty(algorithmUsed))
+            {
+                extractBase64EncodedHash = extractEncodedPassword(prefixEncodedPasswordString);
+
+                base64DecodedPasswordAfterAlgorithm =
+                        PREFIX + algorithmUsed + SUFFIX + decodeBase64EncodedHashWithHex(extractBase64EncodedHash);
```
Comment (carlspring) [inline strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/main/java/org/carlspring/strongbox/authentication/api/ldap/CustomLdapUserDetailsMapper.java:74]:
```suggestion
                base64DecodedPasswordAfterAlgorithm = PREFIX + algorithmUsed +
                                                      SUFFIX + decodeBase64EncodedHashWithHex(extractBase64EncodedHash);
```

File: strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/main/java/org/carlspring/strongbox/authentication/api/ldap/CustomLdapUserDetailsMapper.java [hunk 23]
```diff
@@ -0,0 +1,150 @@
...
+            }
+            else
+            {
+                base64DecodedPasswordAfterAlgorithm = new String(
+                        java.util.Base64.getDecoder().decode(Utf8.encode(extractBase64EncodedHash)));
```
Comment (carlspring) [inline strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/main/java/org/carlspring/strongbox/authentication/api/ldap/CustomLdapUserDetailsMapper.java:79]:
```suggestion
                base64DecodedPasswordAfterAlgorithm = new String(Base64.getDecoder().decode(Utf8.encode(extractBase64EncodedHash)));
```

File: strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/main/java/org/carlspring/strongbox/authentication/api/ldap/CustomLdapUserDetailsMapper.java [hunk 24]
```diff
@@ -0,0 +1,150 @@
...
+
+    private String decodeBase64EncodedHashWithHex(String base64EncodedHash)
+    {
+        try
+        {
+            return new String(Hex.encode(Base64.getDecoder().decode(Utf8.encode(base64EncodedHash))));
+        }
+        catch (Exception ex)
+        {
+            logger.warn("Failed to do Base64Decoding " + ex.getMessage());
```
Comment (carlspring) [inline strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/main/java/org/carlspring/strongbox/authentication/api/ldap/CustomLdapUserDetailsMapper.java:99]:
```suggestion
            logger.warn("Failed to do decode hash using base64! " + ex.getMessage());
```

File: strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/test/java/org/carlspring/strongbox/authentication/api/impl/ldap/LdapAuthenticationProviderTest.java [hunk 25]
```diff
@@ -36,7 +42,7 @@
  * @author sbespalov
  */
 @SpringBootTest
-@ContextHierarchy({ @ContextConfiguration(classes = UsersConfig.class),
+@ContextHierarchy({ @ContextConfiguration(classes = {UsersConfig.class, StrongboxSecurityConfig.class}),
                     @ContextConfiguration(locations = "classpath:/ldapServerApplicationContext.xml"),
                     @ContextConfiguration(initializers = LdapAuthenticationProviderTest.TestContextInitializer.class, locations = "classpath:/org/carlspring/strongbox/authentication/external/ldap/strongbox-authentication-providers.xml") })
```
Comment (carlspring) [inline strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/test/java/org/carlspring/strongbox/authentication/api/impl/ldap/LdapAuthenticationProviderTest.java:47]:
```suggestion
@ContextHierarchy({ @ContextConfiguration(classes = {UsersConfig.class, StrongboxSecurityConfig.class}),
                    @ContextConfiguration(locations = "classpath:/ldapServerApplicationContext.xml"),
                    @ContextConfiguration(initializers = LdapAuthenticationProviderTest.TestContextInitializer.class,
                                          locations = "classpath:/org/carlspring/strongbox/authentication/external/ldap/strongbox-authentication-providers.xml") })
```

File: strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/test/java/org/carlspring/strongbox/authentication/api/impl/ldap/LdapAuthenticationProviderTest.java [hunk 26]
```diff
@@ -51,6 +57,17 @@
...
+    @Inject
+    private PasswordEncoder passwordEncoder;
+
+    private static CustomLdapUserDetailsMapper userDetailsMapper;
+
+
+    @BeforeAll
+    private static void init(){
+        userDetailsMapper = new CustomLdapUserDetailsMapper();
+    }
```
Comment (carlspring) [inline strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/test/java/org/carlspring/strongbox/authentication/api/impl/ldap/LdapAuthenticationProviderTest.java:69]: Cosmetic: Braces on new lines please. :)
```suggestion
    private static void init()
    {
        userDetailsMapper = new CustomLdapUserDetailsMapper();
    }
```

File: strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/test/java/org/carlspring/strongbox/authentication/api/impl/ldap/LdapAuthenticationProviderTest.java [hunk 27]
```diff
@@ -81,6 +98,81 @@ public void embeddedLdapServerRegistersExpectedAuthenticationProvider()
...
+
+    @Test
+    public void base64EncodedPasswordAfterAlgorithmShouldWork()
+    {
+        userDetailsMapper.setBase64EncodedPassword(true);
+        ldapUserDetailsService.setUserDetailsMapper(userDetailsMapper);
+        UserDetails ldapUser = ldapUserDetailsService.loadUserByUsername("base64encoded-issue-1840");
+        assertThat(ldapUser).isInstanceOf(LdapUserDetailsImpl.class);
+        LdapUserDetails ldapUserDetails = (LdapUserDetailsImpl) ldapUser;
```
Comment (carlspring) [inline strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/test/java/org/carlspring/strongbox/authentication/api/impl/ldap/LdapAuthenticationProviderTest.java:111]:
```suggestion
        UserDetails ldapUser = ldapUserDetailsService.loadUserByUsername("base64encoded-issue-1840");
        
        assertThat(ldapUser).isInstanceOf(LdapUserDetailsImpl.class);
        
        LdapUserDetails ldapUserDetails = (LdapUserDetailsImpl) ldapUser;
```

File: strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/test/java/org/carlspring/strongbox/authentication/api/impl/ldap/LdapAuthenticationProviderTest.java [hunk 28]
```diff
@@ -81,6 +98,81 @@ public void embeddedLdapServerRegistersExpectedAuthenticationProvider()
...
+
+    @Test
+    public void base64EncodedPasswordAfterAlgorithmShouldFail()
+    {
+        ldapUserDetailsService.setUserDetailsMapper(userDetailsMapper);
+        userDetailsMapper.setBase64EncodedPassword(false);
+        UserDetails ldapUser = ldapUserDetailsService.loadUserByUsername("base64encoded-issue-1840");
+        assertThat(ldapUser).isInstanceOf(LdapUserDetailsImpl.class);
+        LdapUserDetails ldapUserDetails = (LdapUserDetailsImpl) ldapUser;
+        assertThat(passwordEncoder.matches("password", ldapUserDetails.getPassword())).isEqualTo(false);
```
Comment (carlspring) [inline strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/test/java/org/carlspring/strongbox/authentication/api/impl/ldap/LdapAuthenticationProviderTest.java:136]:
```suggestion
        ldapUserDetailsService.setUserDetailsMapper(userDetailsMapper);
        
        userDetailsMapper.setBase64EncodedPassword(false);
        
        UserDetails ldapUser = ldapUserDetailsService.loadUserByUsername("base64encoded-issue-1840");
        
        assertThat(ldapUser).isInstanceOf(LdapUserDetailsImpl.class);
        
        LdapUserDetails ldapUserDetails = (LdapUserDetailsImpl) ldapUser;
        
        assertThat(passwordEncoder.matches("password", ldapUserDetails.getPassword())).isEqualTo(false);
```

File: strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/test/java/org/carlspring/strongbox/authentication/api/impl/ldap/LdapAuthenticationProviderTest.java [hunk 29]
```diff
@@ -81,6 +98,81 @@ public void embeddedLdapServerRegistersExpectedAuthenticationProvider()
...
+    }
+
+    @Test
+    public void base64EncodedPasswordWithAlgorithmShouldWork()
+    {
+        userDetailsMapper.setBase64EncodedPassword(true);
+        ldapUserDetailsService.setUserDetailsMapper(userDetailsMapper);
+        UserDetails ldapUser = ldapUserDetailsService.loadUserByUsername("base64withalgorithm-issue-1840");
+
+        assertThat(ldapUser).isInstanceOf(LdapUserDetailsImpl.class);
```
Comment (carlspring) [inline strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/test/java/org/carlspring/strongbox/authentication/api/impl/ldap/LdapAuthenticationProviderTest.java:146]: Please, always add an extra line before and after assertions (or assertion blocks). This makes it easier to read and review. Thanks! :)
```suggestion
        assertThat(ldapUser).isInstanceOf(LdapUserDetailsImpl.class);
        
```

File: strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/test/java/org/carlspring/strongbox/authentication/api/impl/ldap/LdapAuthenticationProviderTest.java [hunk 30]
```diff
@@ -81,6 +98,81 @@ public void embeddedLdapServerRegistersExpectedAuthenticationProvider()
...
+    public void base64EncodedPasswordWithAlgorithmShouldFail()
+    {
+        ldapUserDetailsService.setUserDetailsMapper(userDetailsMapper);
+        userDetailsMapper.setBase64EncodedPassword(false);
+        UserDetails ldapUser = ldapUserDetailsService.loadUserByUsername("base64withalgorithm-issue-1840");
+        assertThat(ldapUser).isInstanceOf(LdapUserDetailsImpl.class);
+        LdapUserDetails ldapUserDetails = (LdapUserDetailsImpl) ldapUser;
+        Exception thrown = assertThrows(
+                IllegalArgumentException.class,
+                () -> passwordEncoder.matches("password", ldapUserDetails.getPassword()), "There is no PasswordEncoder mapped for the id \"null\"");
```
Comment (carlspring) [inline strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/test/java/org/carlspring/strongbox/authentication/api/impl/ldap/LdapAuthenticationProviderTest.java:173]:
```suggestion
        ldapUserDetailsService.setUserDetailsMapper(userDetailsMapper);
        
        userDetailsMapper.setBase64EncodedPassword(false);
        
        UserDetails ldapUser = ldapUserDetailsService.loadUserByUsername("base64withalgorithm-issue-1840");
        
        assertThat(ldapUser).isInstanceOf(LdapUserDetailsImpl.class);
        
        LdapUserDetails ldapUserDetails = (LdapUserDetailsImpl) ldapUser;
        
        Exception thrown = assertThrows(
                IllegalArgumentException.class,
                () -> passwordEncoder.matches("password", ldapUserDetails.getPassword()), "There is no PasswordEncoder mapped for the id \"null\"");
```

File: strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/test/java/org/carlspring/strongbox/authentication/api/ldap/CustomLdapUserDetailsMapperTest.java [hunk 31]
```diff
@@ -0,0 +1,41 @@
...
+        CustomLdapUserDetailsMapper userDetailsMapper = new CustomLdapUserDetailsMapper();
+        userDetailsMapper.setBase64EncodedPassword(false);
+        String encodedPassword = userDetailsMapper.mapPassword("{MD5}X03MO1qnZdYdgyfeuILPmQ==");
+        assertThat(encodedPassword).isEqualTo("{MD5}X03MO1qnZdYdgyfeuILPmQ==");
+
+        encodedPassword = userDetailsMapper.mapPassword("e2JjcnlwdH0kMmEkMTAkbHB3bHh5anZYS3pOMWNjQ3J3MlBCdVp4LmVWZXNXYmZtVGJzckNib01VLmdzTldWY1pXTWk=");
+        assertThat(encodedPassword).isEqualTo("e2JjcnlwdH0kMmEkMTAkbHB3bHh5anZYS3pOMWNjQ3J3MlBCdVp4LmVWZXNXYmZtVGJzckNib01VLmdzTldWY1pXTWk=");
+
+        encodedPassword = userDetailsMapper.mapPassword("{SHA-256}{mujKRdqeWWYAWhczNwVnBl6L6dHNwWO5eIGZ/G7pnBg=}bb63813f5b6f64ae306ebbbb23dcbb1c6f49eb9b989fc466b1b1a24a011bb2ce");
+        assertThat(encodedPassword).isEqualTo("{SHA-256}{mujKRdqeWWYAWhczNwVnBl6L6dHNwWO5eIGZ/G7pnBg=}bb63813f5b6f64ae306ebbbb23dcbb1c6f49eb9b989fc466b1b1a24a011bb2ce");
```
Comment (carlspring) [inline strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/test/java/org/carlspring/strongbox/authentication/api/ldap/CustomLdapUserDetailsMapperTest.java:26]:
```suggestion
        String encodedPassword = userDetailsMapper.mapPassword("{MD5}X03MO1qnZdYdgyfeuILPmQ==");
        
        assertThat(encodedPassword).isEqualTo("{MD5}X03MO1qnZdYdgyfeuILPmQ==");

        encodedPassword = userDetailsMapper.mapPassword("e2JjcnlwdH0kMmEkMTAkbHB3bHh5anZYS3pOMWNjQ3J3MlBCdVp4LmVWZXNXYmZtVGJzckNib01VLmdzTldWY1pXTWk=");
        assertThat(encodedPassword).isEqualTo("e2JjcnlwdH0kMmEkMTAkbHB3bHh5anZYS3pOMWNjQ3J3MlBCdVp4LmVWZXNXYmZtVGJzckNib01VLmdzTldWY1pXTWk=");

        encodedPassword = userDetailsMapper.mapPassword("{SHA-256}{mujKRdqeWWYAWhczNwVnBl6L6dHNwWO5eIGZ/G7pnBg=}bb63813f5b6f64ae306ebbbb23dcbb1c6f49eb9b989fc466b1b1a24a011bb2ce");
        
        assertThat(encodedPassword).isEqualTo("{SHA-256}{mujKRdqeWWYAWhczNwVnBl6L6dHNwWO5eIGZ/G7pnBg=}bb63813f5b6f64ae306ebbbb23dcbb1c6f49eb9b989fc466b1b1a24a011bb2ce");
```

File: strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/test/java/org/carlspring/strongbox/authentication/api/ldap/CustomLdapUserDetailsMapperTest.java [hunk 32]
```diff
@@ -0,0 +1,41 @@
...
+        CustomLdapUserDetailsMapper userDetailsMapper = new CustomLdapUserDetailsMapper();
+        userDetailsMapper.setBase64EncodedPassword(true);
+        String encodedPassword = userDetailsMapper.mapPassword("{MD5}X03MO1qnZdYdgyfeuILPmQ==");
+        assertThat(encodedPassword).isEqualTo("{MD5}5f4dcc3b5aa765d61d8327deb882cf99");
+
+        encodedPassword = userDetailsMapper.mapPassword("e2JjcnlwdH0kMmEkMTAkbHB3bHh5anZYS3pOMWNjQ3J3MlBCdVp4LmVWZXNXYmZtVGJzckNib01VLmdzTldWY1pXTWk=");
+        assertThat(encodedPassword).isEqualTo("{bcrypt}$2a$10$lpwlxyjvXKzN1ccCrw2PBuZx.eVesWbfmTbsrCboMU.gsNWVcZWMi");
+
+    }
+}
```
Comment (carlspring) [inline strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/test/java/org/carlspring/strongbox/authentication/api/ldap/CustomLdapUserDetailsMapperTest.java:41]: Please, make sure that files end with an empty line.
```suggestion
}

```

File: strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/test/java/org/carlspring/strongbox/authentication/api/ldap/CustomLdapUserDetailsMapperTest.java [hunk 33]
```diff
@@ -0,0 +1,41 @@
...
+    @Test
+    void testMapPasswordBase64EncodedTrue()
+    {
+        CustomLdapUserDetailsMapper userDetailsMapper = new CustomLdapUserDetailsMapper();
+        userDetailsMapper.setBase64EncodedPassword(true);
+        String encodedPassword = userDetailsMapper.mapPassword("{MD5}X03MO1qnZdYdgyfeuILPmQ==");
+        assertThat(encodedPassword).isEqualTo("{MD5}5f4dcc3b5aa765d61d8327deb882cf99");
+
+        encodedPassword = userDetailsMapper.mapPassword("e2JjcnlwdH0kMmEkMTAkbHB3bHh5anZYS3pOMWNjQ3J3MlBCdVp4LmVWZXNXYmZtVGJzckNib01VLmdzTldWY1pXTWk=");
+        assertThat(encodedPassword).isEqualTo("{bcrypt}$2a$10$lpwlxyjvXKzN1ccCrw2PBuZx.eVesWbfmTbsrCboMU.gsNWVcZWMi");
```
Comment (carlspring) [inline strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/test/java/org/carlspring/strongbox/authentication/api/ldap/CustomLdapUserDetailsMapperTest.java:38]:
```suggestion
        String encodedPassword = userDetailsMapper.mapPassword("{MD5}X03MO1qnZdYdgyfeuILPmQ==");
        
        assertThat(encodedPassword).isEqualTo("{MD5}5f4dcc3b5aa765d61d8327deb882cf99");

        encodedPassword = userDetailsMapper.mapPassword("e2JjcnlwdH0kMmEkMTAkbHB3bHh5anZYS3pOMWNjQ3J3MlBCdVp4LmVWZXNXYmZtVGJzckNib01VLmdzTldWY1pXTWk=");
        
        assertThat(encodedPassword).isEqualTo("{bcrypt}$2a$10$lpwlxyjvXKzN1ccCrw2PBuZx.eVesWbfmTbsrCboMU.gsNWVcZWMi");
```

File: strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/test/resources/org/carlspring/strongbox/authentication/api/impl/ldap/lapt.properties [hunk 34]
```diff
@@ -16,3 +16,4 @@ strongbox.authentication.ldap.authorities.convertToUpperCase=false
 strongbox.authentication.ldap.authorities.groupRoleAttribute=cn
 strongbox.authentication.ldap.authorities.rolePrefix=
 strongbox.authentication.ldap.authorities.searchSubtree=true
+strongbox.authentication.ldap.base64EncodedPassword=false
```
Comment (carlspring) [inline strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/test/resources/org/carlspring/strongbox/authentication/api/impl/ldap/lapt.properties:19]: What is this used for exactly?
Shouldn't it be able to guess this automatically?

File: strongbox-web-core/src/test/java/org/carlspring/strongbox/controllers/layout/nuget/NugetArtifactControllerTest.java [hunk 35]
```diff
@@ -461,6 +461,7 @@ public MockMvcRequestSpecification createPushRequest(byte[] packageContent)
     }
 
     @Test
+    @Disabled
```
Comment (carlspring) [inline strongbox-web-core/src/test/java/org/carlspring/strongbox/controllers/layout/nuget/NugetArtifactControllerTest.java:464]: Is this in relation to #1960 ?

File: strongbox-web-core/src/test/java/org/carlspring/strongbox/controllers/layout/nuget/NugetArtifactControllerTest.java [hunk 36]
```diff
@@ -507,6 +508,7 @@ public void testRemoteProxyGroup()
...
```
Comment (carlspring) [inline strongbox-web-core/src/test/java/org/carlspring/strongbox/controllers/layout/nuget/NugetArtifactControllerTest.java:511]: ...And this?

File: strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/test/resources/org/carlspring/strongbox/authentication/api/impl/ldap/lapt.properties (hunk 34 above)
Comment (sbespalov) [reply strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/test/resources/org/carlspring/strongbox/authentication/api/impl/ldap/lapt.properties:19]: @carlspring we talked about this with @steve-todorov and agreed to have it like this. The thing is that it's not obvious how to guess that the string is base64 encoded.

**Review by sbespalov — CHANGES_REQUESTED** [review]
@madhukarbharti thanks for the changes with `CustomLdapUserDetailsMapper`, it looks good at most. Please have a look at review comments. Also I suggest to resolve formatting code suggestions from @carlspring at first because it brings some noise and makes hard to review. I will review one more time after this.

File: strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/test/java/org/carlspring/strongbox/authentication/api/impl/ldap/LdapAuthenticationProviderTest.java [hunk 37]
```diff
@@ -81,6 +98,81 @@ public void embeddedLdapServerRegistersExpectedAuthenticationProvider()
...
+        assertThat(ldapUserDetails.getPassword()).isEqualTo("{MD5}5f4dcc3b5aa765d61d8327deb882cf99");
+        assertThat(passwordEncoder.matches("password", ldapUserDetails.getPassword())).isEqualTo(true);
+
+        assertThat(((List<SimpleGrantedAuthority>) ldapUser.getAuthorities()))
+                .contains(
+                        new SimpleGrantedAuthority(SystemRole.REPOSITORY_MANAGER.name()),
+                        new SimpleGrantedAuthority("USER_ROLE")
+                );
+
+        userDetailsMapper.setBase64EncodedPassword(false);
```
[the remark this answers is not in the document]
Comment (madhukarbharti) [reply strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/test/java/org/carlspring/strongbox/authentication/api/impl/ldap/LdapAuthenticationProviderTest.java:125]: if we set it to true another password matching will fail if it is not encoded. So in UT enabling and disabling to test decoding is also working

File: strongbox-resources/strongbox-storage-api-resources/src/main/resources/etc/conf/strongbox-authentication-providers.yaml [hunk 38]
```diff
@@ -37,3 +37,4 @@ strongbox:
         groupRoleAttribute: cn
         rolePrefix: ''
         searchSubtree: true
+      base64EncodedPassword: false
```
[the remark this answers is not in the document]
Comment (madhukarbharti) [reply strongbox-resources/strongbox-storage-api-resources/src/main/resources/etc/conf/strongbox-authentication-providers.yaml:40]: This is defined in the same file, do you want in some other file?

File: strongbox-web-core/src/test/java/org/carlspring/strongbox/controllers/layout/nuget/NugetArtifactControllerTest.java (hunk 36 above)
Comment (madhukarbharti) [reply strongbox-web-core/src/test/java/org/carlspring/strongbox/controllers/layout/nuget/NugetArtifactControllerTest.java:511]: Yes, it is giving 400 error. So disabled it

Comment (steve-todorov) [reply strongbox-web-core/src/test/java/org/carlspring/strongbox/controllers/layout/nuget/NugetArtifactControllerTest.java:511]: Yes, this is related to #1960 and I've advised @madhukarbharti to temporarily disable this method. On 17th and 18th of November, these tests will be failing 100% of the time. We should revert this before merging (if they've lifted the ban) and in due time we should also look into #1960.

File: strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/test/resources/org/carlspring/strongbox/authentication/api/impl/ldap/lapt.properties (hunk 34 above)
Comment (steve-todorov) [reply strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/test/resources/org/carlspring/strongbox/authentication/api/impl/ldap/lapt.properties:19]: > The thing is that it's not obvious how to guess that the string is base64 encoded

I agree it would be tricky to auto guess indeed. The closest to auto-guessing we come to is to use fallbacks which would also allow support for both base64 and non-base64 encoded passwords. The TL;DR version:

1. Get user password from LDAP
2. Inside the `CustomLdapUserDetailsMapper`
    1. Try to compare passwords using regular Spring Password Encoder - if it doesn't succeed then `ii.`
    2. Try to compare passwords using the newly created 

Other than that, I don't see any other way we can automate it.

Comment (carlspring) [reply strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/test/resources/org/carlspring/strongbox/authentication/api/impl/ldap/lapt.properties:19]: @sbespalov , @madhukarbharti ,

The property approach is, unfortunately, not good enough. Let me explain why...

In large organizations, you usually have to define more than one LDAP server (different teams may be in different locations and jurisdictions of the respective organization). For example, in the corporation's European office, they might have an OpenLDAP server that is part of the farm, but, in the US office, they might be using AD (ActiveDirectory). One of the chained servers in the farm might be using base64, but the other might not and when we do it this way, this will break it for the other server.

At some point we will need to add support for more than one LDAP server and when that time comes, we'll have to re-work this, if we do it like this.

I agree with Stevie's proposal about this -- we should do our best to guess things and if `2.i` and `2.ii` don't work, well, the users of our application will (then) simply have to work it out or report an issue with the problem they are facing, so we can investigate and improve our implementation. This way we'll have done our best to support them through our implementation, so that they have less to worry about.

File: strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/test/java/org/carlspring/strongbox/authentication/api/impl/ldap/LdapAuthenticationProviderTest.java [hunk 39]
```diff
@@ -71,19 +79,56 @@ public void embeddedLdapServerRegistersExpectedAuthenticationProvider()
...
+        UserDetails ldapUser = ldapUserDetailsService.loadUserByUsername("base64withalgorithm-issue-1840");
+
+        assertThat(ldapUser).isInstanceOf(LdapUserDetailsImpl.class);
+
+        LdapUserDetails ldapUserDetails = (LdapUserDetailsImpl) ldapUser;
+
+        Exception thrown = assertThrows(
+                IllegalArgumentException.class,
+                () -> passwordEncoder.matches("password", ldapUserDetails.getPassword()),
+                "There is no PasswordEncoder mapped for the id \"null\"");
```
Comment (carlspring) [inline strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/test/java/org/carlspring/strongbox/authentication/api/impl/ldap/LdapAuthenticationProviderTest.java:125]:
```suggestion
        Exception thrown = assertThrows(IllegalArgumentException.class,
                                        () -> passwordEncoder.matches("password", ldapUserDetails.getPassword()),
                                        "There is no PasswordEncoder mapped for the id \"null\"");
```

File: strongbox-web-core/src/test/java/org/carlspring/strongbox/controllers/layout/nuget/NugetArtifactControllerTest.java (hunk 36 above)
Comment (carlspring) [reply strongbox-web-core/src/test/java/org/carlspring/strongbox/controllers/layout/nuget/NugetArtifactControllerTest.java:511]: Okay, thanks for the clarification! :)

File: strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/test/resources/org/carlspring/strongbox/authentication/api/impl/ldap/lapt.properties (hunk 34 above)
Comment (madhukarbharti) [reply strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/test/resources/org/carlspring/strongbox/authentication/api/impl/ldap/lapt.properties:19]: @carlspring @steve-todorov @sbespalov 

Based on the current approach where we have custom UserDetailMapper we can just map a password either with what has been passed or decoded base64. If we validate the password in our custom mapper will it not be duplicate password validations best case 2 times, else 3 times? We can have password validation logic in the new custom mapper to get away from the property. It will do:
I.  Verifies password matches, then return the same password
II. If `I` fails, based on password hash it will decode and match, if matches return decoded string else return an actual hash password

Let me know if we can change this way?

Comment (sbespalov) [reply strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/test/resources/org/carlspring/strongbox/authentication/api/impl/ldap/lapt.properties:19]: @carlspring we already able to support many LDAP servers, this is just a matter of configuration. So regarding this  `strongbox.authentication.ldap.base64EncodedPassword` property it could have different values for different LDAP instances like below:
```
//LDAP1 server configuration
strongbox.authentication.ldap1.url=ldap://ldap1:53389/dc=carlspring,dc=com
...
strongbox.authentication.ldap1.base64EncodedPassword=false

//LDAP2 server configuration
strongbox.authentication.ldap2.url=ldap://ldap2:53389/dc=carlspring,dc=com
strongbox.authentication.ldap2.base64EncodedPassword=true
```
As for @steve-todorov proposal it seems not really good to have `PasswordEncoder` instance at `CustomLdapUserDetailsMapper` and there are many reasons of this. First is that I don't understand how it suppose to work because we have no "provided" password in `LdapUserDetailsMapper` so we have nothing to compare with `PasswordEncoder`, another thing is that it seems like a bad architectural design because it brings high cohesion between LDAP mappings and authentication process and will be confusing in general.

Summarizing things I would suggest to think in the future about how we could improve this with distinction of base64 encoded passwords. As for me then manual configuration seems relevant as well and have it's own advantages.

File: strongbox-resources/strongbox-storage-api-resources/src/main/resources/etc/conf/strongbox-authentication-providers.yaml (hunk 38 above)
[the remark this answers is not in the document]
Comment (sbespalov) [reply strongbox-resources/strongbox-storage-api-resources/src/main/resources/etc/conf/strongbox-authentication-providers.yaml:40]: ok, sorry for confusion

File: strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/test/java/org/carlspring/strongbox/authentication/api/impl/ldap/LdapAuthenticationProviderTest.java (hunk 28 above)
Comment (sbespalov) [reply strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/test/java/org/carlspring/strongbox/authentication/api/impl/ldap/LdapAuthenticationProviderTest.java]: @carlspring why you suggest this empty lines?

File: strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/main/java/org/carlspring/strongbox/authentication/api/ldap/CustomLdapUserDetailsMapper.java [hunk 40]
```diff
@@ -0,0 +1,140 @@
...
+
+    private String decodeBase64EncodedHashWithHex(String base64EncodedHash)
+    {
+        try
+        {
+            return new String(Hex.encode(Base64.getDecoder().decode(Utf8.encode(base64EncodedHash))));
+        }
+        catch (Exception ex)
+        {
+            logger.warn("decode hash using base64! " + ex.getMessage());
```
Comment (sbespalov) [inline strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/main/java/org/carlspring/strongbox/authentication/api/ldap/CustomLdapUserDetailsMapper.java:87]: @madhukarbharti please log the exception as well
```suggestion
            logger.warn("decode hash using base64! " + ex.getMessage(), e);
```

Comment (sbespalov) [reply strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/main/java/org/carlspring/strongbox/authentication/api/ldap/CustomLdapUserDetailsMapper.java:87]: please fix this

File: strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/main/java/org/carlspring/strongbox/authentication/api/ldap/CustomLdapUserDetailsMapper.java [hunk 41]
```diff
@@ -0,0 +1,150 @@
...
+            {
+                base64DecodedPasswordAfterAlgorithm = new String(
+                        java.util.Base64.getDecoder().decode(Utf8.encode(extractBase64EncodedHash)));
+            }
+
+            return base64DecodedPasswordAfterAlgorithm;
+        }
+        catch (Exception e)
+        {
+            logger.warn("Failed to match password after decoding base64encoded hash after algorithm");
```
[the remark this answers is not in the document]
Comment (sbespalov) [reply strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/main/java/org/carlspring/strongbox/authentication/api/ldap/CustomLdapUserDetailsMapper.java]: please fix this

File: strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/test/java/org/carlspring/strongbox/authentication/api/ldap/CustomLdapUserDetailsMapperTest.java [hunk 42]
```diff
@@ -0,0 +1,45 @@
...
+
+import org.junit.jupiter.api.Test;
+import static org.assertj.core.api.Assertions.assertThat;
+
+/**
+ * Test class of CustomLdapUserDetailsMapper
+ * @author mbharti
+ * @date 17/11/20
+ */
+class CustomLdapUserDetailsMapperTest
```
Comment (sbespalov) [inline strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/test/java/org/carlspring/strongbox/authentication/api/ldap/CustomLdapUserDetailsMapperTest.java:11]: why not `public`?

File: strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/test/java/org/carlspring/strongbox/authentication/api/impl/ldap/LdapAuthenticationBase64EncodedTest.java [hunk 43]
```diff
@@ -0,0 +1,134 @@
...
+            try (InputStream is = LdapAuthenticationProviderTest.class.getResourceAsStream("lapt.properties"))
+            {
+                properties.load(is);
+            }
+            catch (Exception ex)
+            {
+                throw new UndeclaredThrowableException(ex);
+            }
+
+            properties.put(BASE64_ENCODING_KEY, true);
```
Comment (sbespalov) [inline strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/test/java/org/carlspring/strongbox/authentication/api/impl/ldap/LdapAuthenticationBase64EncodedTest.java:129]: @madhukarbharti you shouldn't do it like this here as well. Please use another properties file for this test instead. It should be `labet.properties` and have `strongbox.authentication.ldap.base64EncodedPassword=true`.

File: strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/main/java/org/carlspring/strongbox/authentication/api/ldap/CustomLdapUserDetailsMapper.java (hunk 40 above)
Comment (madhukarbharti) [reply strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/main/java/org/carlspring/strongbox/authentication/api/ldap/CustomLdapUserDetailsMapper.java]: taken care

Comment (sbespalov) [reply strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/main/java/org/carlspring/strongbox/authentication/api/ldap/CustomLdapUserDetailsMapper.java]: thanks

**Review by sbespalov — APPROVED** [review]
LGTM now, thanks @madhukarbharti !

File: strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/test/resources/org/carlspring/strongbox/authentication/api/impl/ldap/lapt.properties (hunk 34 above)
Comment (steve-todorov) [reply strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/test/resources/org/carlspring/strongbox/authentication/api/impl/ldap/lapt.properties:19]: You are right. The correct place for such a logic would probably be in an  LdapAuthenticationManager || LdapAuthenticationProvider as a custom PasswordEncoder but from what I see we currently don't have a way to do it yet and would require a refactoring. 

Let's go with what Sergey suggests for now.

**Comment by steve-todorov** [comment]
@sbespalov thanks for reviewing! I'll try it with an actual LDAP server orver the weekend and see if it works. 

@carlspring do you have anything to add?

@madhukarbharti can you please remove the `@Disabled` annotations in the Nuget tests? It should be working now as the ban should have been lifted now.

File: strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/main/java/org/carlspring/strongbox/authentication/api/ldap/CustomLdapUserDetailsMapper.java [hunk 44]
```diff
@@ -0,0 +1,140 @@
...
+        {
+            String algorithmUsed = extractId(prefixEncodedPasswordString);
+            String extractBase64EncodedHash = prefixEncodedPasswordString;
+
+            if (!StringUtils.isEmpty(algorithmUsed))
+            {
+                extractBase64EncodedHash = extractEncodedPassword(prefixEncodedPasswordString);
+
+                return PREFIX + algorithmUsed + SUFFIX
+                       + decodeBase64EncodedHashWithHex(extractBase64EncodedHash);
```
Comment (carlspring) [inline strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/main/java/org/carlspring/strongbox/authentication/api/ldap/CustomLdapUserDetailsMapper.java:64]:
```suggestion
                return PREFIX + algorithmUsed + SUFFIX + decodeBase64EncodedHashWithHex(extractBase64EncodedHash);
```

File: strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/test/java/org/carlspring/strongbox/authentication/api/impl/ldap/LdapAuthenticationBase64EncodedTest.java [hunk 45]
```diff
@@ -0,0 +1,130 @@
...
+
+        assertThat(ldapUserDetails.getDn()).isEqualTo("uid=base64encoded-issue-1840,ou=Users,dc=carlspring,dc=com");
+
+        assertThat(ldapUserDetails.getUsername()).isEqualTo("base64encoded-issue-1840");
+
+        assertThat(ldapUserDetails.getPassword()).isEqualTo("{MD5}5f4dcc3b5aa765d61d8327deb882cf99");
+
+        assertThat(passwordEncoder.matches("password", ldapUserDetails.getPassword())).isEqualTo(true);
+
+        assertThat(((List<SimpleGrantedAuthority>) ldapUser.getAuthorities()))
```
Comment (carlspring) [inline strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/test/java/org/carlspring/strongbox/authentication/api/impl/ldap/LdapAuthenticationBase64EncodedTest.java:71]:
```suggestion
        assertThat(ldapUserDetails.getDn()).isEqualTo("uid=base64encoded-issue-1840,ou=Users,dc=carlspring,dc=com");
        assertThat(ldapUserDetails.getUsername()).isEqualTo("base64encoded-issue-1840");
        assertThat(ldapUserDetails.getPassword()).isEqualTo("{MD5}5f4dcc3b5aa765d61d8327deb882cf99");
        assertThat(passwordEncoder.matches("password", ldapUserDetails.getPassword())).isEqualTo(true);
        assertThat(((List<SimpleGrantedAuthority>) ldapUser.getAuthorities()))
```

File: strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/test/java/org/carlspring/strongbox/authentication/api/impl/ldap/LdapAuthenticationBase64EncodedTest.java [hunk 46]
```diff
@@ -0,0 +1,130 @@
...
+                .contains(
+                        new SimpleGrantedAuthority(SystemRole.REPOSITORY_MANAGER.name()),
+                        new SimpleGrantedAuthority("USER_ROLE")
+                );
```
Comment (carlspring) [inline strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/test/java/org/carlspring/strongbox/authentication/api/impl/ldap/LdapAuthenticationBase64EncodedTest.java:75]:
```suggestion
                .contains(new SimpleGrantedAuthority(SystemRole.REPOSITORY_MANAGER.name()),
                          new SimpleGrantedAuthority("USER_ROLE"));
```

File: strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/test/java/org/carlspring/strongbox/authentication/api/impl/ldap/LdapAuthenticationBase64EncodedTest.java [hunk 47]
```diff
@@ -0,0 +1,130 @@
...
+        assertThat(ldapUserDetails.getPassword()).isEqualTo(
+                "{bcrypt}$2a$10$lpwlxyjvXKzN1ccCrw2PBuZx.eVesWbfmTbsrCboMU.gsNWVcZWMi");
+
+        assertThat(passwordEncoder.matches("password", ldapUserDetails.getPassword())).isEqualTo(true);
+
+        assertThat(((List<SimpleGrantedAuthority>) ldapUser.getAuthorities()))
+                .contains(
+                        new SimpleGrantedAuthority(SystemRole.REPOSITORY_MANAGER.name()),
+                        new SimpleGrantedAuthority("USER_ROLE")
+                );
```
Comment (carlspring) [inline strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/test/java/org/carlspring/strongbox/authentication/api/impl/ldap/LdapAuthenticationBase64EncodedTest.java:102]:
```suggestion
        assertThat(ldapUserDetails.getDn()).isEqualTo(
                "uid=base64withalgorithm-issue-1840,ou=Users,dc=carlspring,dc=com");
        assertThat(ldapUserDetails.getUsername()).isEqualTo("base64withalgorithm-issue-1840");
        assertThat(ldapUserDetails.getPassword()).isEqualTo(
                "{bcrypt}$2a$10$lpwlxyjvXKzN1ccCrw2PBuZx.eVesWbfmTbsrCboMU.gsNWVcZWMi");
        assertThat(passwordEncoder.matches("password", ldapUserDetails.getPassword())).isEqualTo(true);
        assertThat(((List<SimpleGrantedAuthority>) ldapUser.getAuthorities()))
                .contains(new SimpleGrantedAuthority(SystemRole.REPOSITORY_MANAGER.name()),
                          new SimpleGrantedAuthority("USER_ROLE"));
```

File: strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/test/java/org/carlspring/strongbox/authentication/api/impl/ldap/LdapAuthenticationProviderTest.java [hunk 48]
```diff
@@ -36,7 +40,8 @@
  * @author sbespalov
  */
 @SpringBootTest
-@ContextHierarchy({ @ContextConfiguration(classes = UsersConfig.class),
+@ContextHierarchy({ @ContextConfiguration(classes = { UsersConfig.class,
+                                                      StrongboxSecurityConfig.class }),
                     @ContextConfiguration(locations = "classpath:/ldapServerApplicationContext.xml"),
                     @ContextConfiguration(initializers = LdapAuthenticationProviderTest.TestContextInitializer.class, locations = "classpath:/org/carlspring/strongbox/authentication/external/ldap/strongbox-authentication-providers.xml") })
```
Comment (carlspring) [inline strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/test/java/org/carlspring/strongbox/authentication/api/impl/ldap/LdapAuthenticationProviderTest.java:46]:
```suggestion
                    @ContextConfiguration(initializers = LdapAuthenticationProviderTest.TestContextInitializer.class,
                                          locations = "classpath:/org/carlspring/strongbox/authentication/external/ldap/strongbox-authentication-providers.xml") })
```

File: strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/test/java/org/carlspring/strongbox/authentication/api/impl/ldap/LdapAuthenticationProviderTest.java [hunk 49]
```diff
@@ -71,19 +79,56 @@ public void embeddedLdapServerRegistersExpectedAuthenticationProvider()
         UserDetails ldapUser = ldapUserDetailsService.loadUserByUsername("przemyslaw.fusik");
 
         assertThat(ldapUser).isInstanceOf(LdapUserDetailsImpl.class);
+
         LdapUserDetails ldapUserDetails = (LdapUserDetailsImpl) ldapUser;
 
         assertThat(ldapUserDetails.getDn()).isEqualTo("uid=przemyslaw.fusik,ou=Users,dc=carlspring,dc=com");
-        assertThat(ldapUserDetails.getPassword()).isEqualTo("{SHA-256}{mujKRdqeWWYAWhczNwVnBl6L6dHNwWO5eIGZ/G7pnBg=}bb63813f5b6f64ae306ebbbb23dcbb1c6f49eb9b989fc466b1b1a24a011bb2ce");
+
```
Comment (carlspring) [inline strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/test/java/org/carlspring/strongbox/authentication/api/impl/ldap/LdapAuthenticationProviderTest.java:86]:
```suggestion
```

File: strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/test/java/org/carlspring/strongbox/authentication/api/impl/ldap/LdapAuthenticationProviderTest.java [hunk 50]
```diff
@@ -71,19 +79,56 @@ public void embeddedLdapServerRegistersExpectedAuthenticationProvider()
...
+        assertThat(ldapUserDetails.getPassword()).isEqualTo(
+                "{SHA-256}{mujKRdqeWWYAWhczNwVnBl6L6dHNwWO5eIGZ/G7pnBg=}bb63813f5b6f64ae306ebbbb23dcbb1c6f49eb9b989fc466b1b1a24a011bb2ce");
+
```
Comment (carlspring) [inline strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/test/java/org/carlspring/strongbox/authentication/api/impl/ldap/LdapAuthenticationProviderTest.java:89]:
```suggestion
```

File: strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/test/java/org/carlspring/strongbox/authentication/api/impl/ldap/LdapAuthenticationProviderTest.java [hunk 51]
```diff
@@ -71,19 +79,56 @@ public void embeddedLdapServerRegistersExpectedAuthenticationProvider()
...
         assertThat(ldapUserDetails.getUsername()).isEqualTo("przemyslaw.fusik");
-        assertThat(((List<SimpleGrantedAuthority>)ldapUser.getAuthorities()))
+
```
Comment (carlspring) [inline strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/test/java/org/carlspring/strongbox/authentication/api/impl/ldap/LdapAuthenticationProviderTest.java:91]:
```suggestion
```

File: strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/test/java/org/carlspring/strongbox/authentication/api/impl/ldap/LdapAuthenticationProviderTest.java [hunk 52]
```diff
@@ -71,19 +79,56 @@ public void embeddedLdapServerRegistersExpectedAuthenticationProvider()
...
+        assertThat(((List<SimpleGrantedAuthority>) ldapUser.getAuthorities()))
                 .contains(
                         new SimpleGrantedAuthority(SystemRole.REPOSITORY_MANAGER.name()),
                         new SimpleGrantedAuthority("USER_ROLE")
                 );
+
```
Comment (carlspring) [inline strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/test/java/org/carlspring/strongbox/authentication/api/impl/ldap/LdapAuthenticationProviderTest.java:97]:
```suggestion
```

File: strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/test/resources/org/carlspring/strongbox/authentication/api/impl/ldap/labet.properties [hunk 53]
```diff
@@ -0,0 +1,19 @@
+strongbox.authentication.ldap.url=ldap://127.0.0.1:53389/dc=carlspring,dc=com
+!strongbox.authentication.ldap.managerDn=cn=manager,ou=users,dc=carlspring,dc=com
```
Comment (carlspring) [inline strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/test/resources/org/carlspring/strongbox/authentication/api/impl/ldap/labet.properties:2]: I assume this is an invalid property...?

File: strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/test/java/org/carlspring/strongbox/authentication/api/impl/ldap/LdapAuthenticationBase64EncodedTest.java [hunk 54]
```diff
@@ -0,0 +1,130 @@
...
+ * Test Class for checking Base64Encoded LDAP password
+ *
+ * @author mbharti
+ * @date 18/11/20
+ */
+@SpringBootTest
+@ContextHierarchy({ @ContextConfiguration(classes = { UsersConfig.class,
+                                                      StrongboxSecurityConfig.class }),
+                    @ContextConfiguration(locations = "classpath:/ldapServerApplicationContext.xml"),
+                    @ContextConfiguration(initializers = LdapAuthenticationBase64EncodedTest.TestContextInitializer.class, locations = "classpath:/org/carlspring/strongbox/authentication/external/ldap/strongbox-authentication-providers.xml") })
```
Comment (carlspring) [inline strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/test/java/org/carlspring/strongbox/authentication/api/impl/ldap/LdapAuthenticationBase64EncodedTest.java:41]:
```suggestion
                    @ContextConfiguration(initializers = LdapAuthenticationBase64EncodedTest.TestContextInitializer.class,
                                          locations = "classpath:/org/carlspring/strongbox/authentication/external/ldap/strongbox-authentication-providers.xml") })
```

File: strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/test/java/org/carlspring/strongbox/authentication/api/impl/ldap/LdapAuthenticationBase64EncodedTest.java [hunk 55]
```diff
@@ -0,0 +1,130 @@
...
+        assertThat(ldapUserDetails.getPassword()).isEqualTo("{MD5}5f4dcc3b5aa765d61d8327deb882cf99");
+
+        assertThat(passwordEncoder.matches("password", ldapUserDetails.getPassword())).isEqualTo(true);
+
+        assertThat(((List<SimpleGrantedAuthority>) ldapUser.getAuthorities()))
+                .contains(
+                        new SimpleGrantedAuthority(SystemRole.REPOSITORY_MANAGER.name()),
+                        new SimpleGrantedAuthority("USER_ROLE")
+                );
+
```
Comment (carlspring) [inline strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/test/java/org/carlspring/strongbox/authentication/api/impl/ldap/LdapAuthenticationBase64EncodedTest.java:76]:
```suggestion
        assertThat(ldapUserDetails.getDn()).isEqualTo("uid=base64encoded-issue-1840,ou=Users,dc=carlspring,dc=com");
        assertThat(ldapUserDetails.getUsername()).isEqualTo("base64encoded-issue-1840");
        assertThat(ldapUserDetails.getPassword()).isEqualTo("{MD5}5f4dcc3b5aa765d61d8327deb882cf99");
        assertThat(passwordEncoder.matches("password", ldapUserDetails.getPassword())).isEqualTo(true);
        assertThat(((List<SimpleGrantedAuthority>) ldapUser.getAuthorities()))
                .contains(new SimpleGrantedAuthority(SystemRole.REPOSITORY_MANAGER.name()),
                          new SimpleGrantedAuthority("USER_ROLE"));
```

File: strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/test/java/org/carlspring/strongbox/authentication/api/impl/ldap/LdapAuthenticationBase64EncodedTest.java [hunk 56]
```diff
@@ -0,0 +1,118 @@
...
+        assertThat(ldapUserDetails.getDn()).isEqualTo(
+                "uid=base64withalgorithm-issue-1840,ou=Users,dc=carlspring,dc=com");
+        assertThat(ldapUserDetails.getUsername()).isEqualTo("base64withalgorithm-issue-1840");
+        assertThat(ldapUserDetails.getPassword()).isEqualTo(
+                "{bcrypt}$2a$10$lpwlxyjvXKzN1ccCrw2PBuZx.eVesWbfmTbsrCboMU.gsNWVcZWMi");
+        assertThat(passwordEncoder.matches("password", ldapUserDetails.getPassword())).isEqualTo(true);
+        assertThat(((List<SimpleGrantedAuthority>) ldapUser.getAuthorities()))
+                .contains(new SimpleGrantedAuthority(SystemRole.REPOSITORY_MANAGER.name()),
+                          new SimpleGrantedAuthority("USER_ROLE"));
+
```
Comment (carlspring) [inline strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/test/java/org/carlspring/strongbox/authentication/api/impl/ldap/LdapAuthenticationBase64EncodedTest.java:91]:
```suggestion
```

File: strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/test/resources/org/carlspring/strongbox/authentication/api/impl/ldap/lapt.properties (hunk 34 above)
Comment (carlspring) [reply strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/test/resources/org/carlspring/strongbox/authentication/api/impl/ldap/lapt.properties:19]: Very well, let's proceed with this as it is.

File: strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/test/resources/org/carlspring/strongbox/authentication/api/impl/ldap/labet.properties (hunk 53 above)
Comment (steve-todorov) [reply strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/test/resources/org/carlspring/strongbox/authentication/api/impl/ldap/labet.properties]: Yes, I've removed it! Thanks! :)

**Comment by madhukarbharti** [comment]
@steve-todorov  Removed the @Disabled annotations in the Nuget tests and updated PR.

**Review by sbespalov — APPROVED** [review]
@madhukarbharti @steve-todorov I think we should merge. Thanks!

**Comment by sbespalov** [comment]
@madhukarbharti could you please squash before merge.

**Review by steve-todorov — APPROVED** [review]
@madhukarbharti thanks for your hard work on this!

// cc: @carlspring ICLA?

**Comment by madhukarbharti** [comment]
@steve-todorov Squashed and Rebased

File: strongbox-security/strongbox-authentication-providers/README.md [hunk 57]
```diff
@@ -1 +1,12 @@
-Strongbox authentication providers enumerates all supported builin authentication providers.
\ No newline at end of file
+# strongbox-authentication-providers
+
+Strongbox authentication providers enumerates all supported buil-in authentication providers.
```
Comment (carlspring) [inline strongbox-security/strongbox-authentication-providers/README.md:3]:
```suggestion
Strongbox authentication providers enumerates all supported built-in authentication providers.
```

**Comment by steve-todorov** [comment]
Congratulations @madhukarbharti! Thanks for your work on this again! :)

**Comment by carlspring** [comment]
@madhukarbharti ,

Thank you very much for all your hard work and congratulations on your first pull request! :)

**Comment by madhukarbharti** [comment]
Thank you so much @carlspring @sbespalov  and @steve-todorov for all support and suggestions. It was really nice to work with you all.
