### PR TITLE
Out of Service Repository Handling

### LINKED ISSUE #1664: "Out of service" storages can not be removed and zombie around
# Steps To Reproduce

1. create a 'proxy repository'
2. set 'Status' to `Out of Service`
3. try to 'Delete Repository"
4. note the error message:
```
Failed to complete request /api/configuration/strongbox/storages/storage-nuget/chocolatey
[object Object]
```

# Expected Behavior

storage should get deleted.

# Environment

* Strongbox Version: `{"strongbox":{"version":"1.0-SNAPSHOT","revision":"eccd13064b1e3bfa"}}`
* OS: `adoptopenjdk/openjdk8:jdk8u232-b09-alpine`

### PR DESCRIPTION
**Pull request by anki2189**
# Pull Request Description

This pull request closes #1664 

# Acceptance Test

* [x] Building the code with `mvn clean install -Dintegration.tests` still works.
* [x] Running `mvn spring-boot:run` in the `strongbox-web-core` still starts up the application correctly.
* [x] Building the code and running the `strongbox-distribution` from a `zip` or `tar.gz` still works.
* [x] The tests in the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) still run properly.

# Questions

* Does this pull request break backward compatibility? 
  * [ ] Yes
  * [x] No

* Does this pull request require other pull requests to be merged first? 
  * [ ] Yes, please see #...
  * [x] No

* Does this require an update of the documentation?
  * [ ] Yes, please see strongbox/strongbox-docs#{PR_NUMBER}
  * [x] No

### CODE REVIEW

File: strongbox-web-core/src/main/java/org/carlspring/strongbox/web/RepositoryMethodArgumentResolver.java [hunk 1]
```diff
@@ -69,7 +71,7 @@ public Object resolveArgument(final MethodParameter parameter,
                                                                            RequestAttributes.SCOPE_REQUEST);
 
         if (repository != null && Objects.equals(repository.getId(), repositoryId) &&
-            Objects.equals(repository.getStorage().getId(), storageId))
+                Objects.equals(repository.getStorage().getId(), storageId))
```
[the remark this answers is not in the document]
Comment (anki2189) [reply strongbox-web-core/src/main/java/org/carlspring/strongbox/web/RepositoryMethodArgumentResolver.java]: I am using formatter provided on wiki , these spaces are introduced by formatter :)

File: strongbox-web-core/src/main/java/org/carlspring/strongbox/web/RepositoryMapping.java [hunk 2]
```diff
@@ -22,4 +22,6 @@
     String storageVariableName() default "storageId";
 
     String repositoryVariableName() default "repositoryId";
+
+    boolean inServiceRepository() default true;
```
[the remark this answers is not in the document]
Comment (anki2189) [reply strongbox-web-core/src/main/java/org/carlspring/strongbox/web/RepositoryMapping.java]: Fixed.

File: strongbox-web-core/src/main/java/org/carlspring/strongbox/web/RepositoryMethodArgumentResolver.java [hunk 3]
```diff
@@ -88,7 +90,7 @@ public Object resolveArgument(final MethodParameter parameter,
             throw new RepositoryNotFoundException(message);
         }
 
-        final boolean inService = repository.isInService();
+        final boolean inService = repositoryMapping.inServiceRepository();
         if (!inService)
```
[the remark this answers is not in the document]
Comment (anki2189) [reply strongbox-web-core/src/main/java/org/carlspring/strongbox/web/RepositoryMethodArgumentResolver.java]: Fixed.

File: strongbox-web-core/src/test/java/org/carlspring/strongbox/web/RepositoryMethodArgumentResolverTest.java [hunk 4]
```diff
@@ -0,0 +1,249 @@
...
+
+        MethodParameter uploadArtifactWithRepositoryMappingMethod = getMethodParameter("uploadArtifactWithRepositoryMapping",
+                                                                                       Repository.class);
+        Repository repository = (Repository) repositoryMethodArgumentResolver.resolveArgument(uploadArtifactWithRepositoryMappingMethod,
+                                                                                              modelAndViewContainer,
+                                                                                              nativeWebRequest,
+                                                                                              webDataBinderFactory);
+        assertNotNull(repository);
+
+        // ServiceUnavailableException Test Case
```
[the remark this answers is not in the document]
Comment (anki2189) [reply strongbox-web-core/src/test/java/org/carlspring/strongbox/web/RepositoryMethodArgumentResolverTest.java]: Moved.

File: strongbox-web-core/src/test/java/org/carlspring/strongbox/web/RepositoryMethodArgumentResolverTest.java [hunk 5]
```diff
@@ -0,0 +1,249 @@
...
+        ServiceUnavailableException serviceUnavailableException = Assertions.assertThrows(ServiceUnavailableException.class,
+                                                                                          () -> repositoryMethodArgumentResolver.resolveArgument(uploadArtifactForRepositoryNotInServiceMethod,
+                                                                                                                                                 modelAndViewContainer,
+                                                                                                                                                 nativeWebRequest,
+                                                                                                                                                 webDataBinderFactory));
+        assertEquals(String.format(RepositoryMethodArgumentResolver.NOT_IN_SERVICE_REPOSITORY_MESSAGE,
+                                   uriTemplateVars.get("storageId"), uriTemplateVars.get("repositoryId")),
+                     serviceUnavailableException.getMessage());
+
+        // StorageNotFoundException Test Case
```
[the remark this answers is not in the document]
Comment (anki2189) [reply strongbox-web-core/src/test/java/org/carlspring/strongbox/web/RepositoryMethodArgumentResolverTest.java]: Moved.

File: strongbox-web-core/src/test/java/org/carlspring/strongbox/web/RepositoryMethodArgumentResolverTest.java [hunk 6]
```diff
@@ -0,0 +1,249 @@
...
+        StorageNotFoundException storageNotFoundException = Assertions.assertThrows(StorageNotFoundException.class,
+                                                                                    () -> repositoryMethodArgumentResolver.resolveArgument(uploadArtifactWithRepositoryMappingMethod,
+                                                                                                                                           modelAndViewContainer,
+                                                                                                                                           nativeWebRequest,
+                                                                                                                                           webDataBinderFactory));
+        assertEquals(String.format(RepositoryMethodArgumentResolver.NOT_FOUND_STORAGE_MESSAGE,
+                                   uriTemplateVars.get("storageId")),
+                     storageNotFoundException.getMessage());
+
+        // RepositoryNotFoundException Test Case
```
[the remark this answers is not in the document]
Comment (anki2189) [reply strongbox-web-core/src/test/java/org/carlspring/strongbox/web/RepositoryMethodArgumentResolverTest.java]: Moved.

File: strongbox-web-core/src/test/java/org/carlspring/strongbox/web/RepositoryMethodArgumentResolverTest.java [hunk 7]
```diff
@@ -0,0 +1,249 @@
...
+        {
+        }
+
+        @PutMapping(path = "/{storageId}/{repositoryId}/uploadArtifactWithRepositoryMappingAndInvalidRepository")
+        void uploadArtifactWithRepositoryMappingAndInvalidRepository(@RepositoryMapping RepositoryData repository)
+        {
+        }
+
+        @PutMapping(path = "/{storageId}/{repositoryId}/uploadArtifactForRepositoryNotInService")
+        void uploadArtifactForRepositoryNotInService(@RepositoryMapping(inServiceRepository = false) Repository repository)
```
[the remark this answers is not in the document]
Comment (anki2189) [reply strongbox-web-core/src/test/java/org/carlspring/strongbox/web/RepositoryMethodArgumentResolverTest.java]: Done.

File: strongbox-web-core/src/main/java/org/carlspring/strongbox/web/RepositoryMethodArgumentResolver.java (hunk 1 above)
[the remark this answers is not in the document]
Comment (steve-todorov) [reply strongbox-web-core/src/main/java/org/carlspring/strongbox/web/RepositoryMethodArgumentResolver.java]: Thanks for reverting it. Unfortunately the latest versions of IntelliJ have issues with alignment. It's a bug on their side and probably related to https://youtrack.jetbrains.com/issue/IDEA-226588 :/

File: strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/configuration/StoragesConfigurationController.java [hunk 8]
```diff
@@ -305,7 +305,7 @@ public ResponseEntity getRepositoryResponseEntity(@RepositoryMapping Repository
     @PreAuthorize("hasAuthority('CONFIGURATION_DELETE_REPOSITORY')")
     @DeleteMapping(value = "/{storageId}/{repositoryId}", produces = { MediaType.TEXT_PLAIN_VALUE,
                                                                        MediaType.APPLICATION_JSON_VALUE })
-    public ResponseEntity removeRepository(@RepositoryMapping Repository repository,
+    public ResponseEntity removeRepository(@RepositoryMapping(allowOutOfServiceRepository = true) Repository repository,
```
Comment (steve-todorov) [inline strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/configuration/StoragesConfigurationController.java]: This change needs to be applied to the `getRepositoryResponseEntity` method as well.

File: strongbox-web-core/src/main/java/org/carlspring/strongbox/web/RepositoryMapping.java [hunk 9]
```diff
@@ -22,4 +22,6 @@
     String storageVariableName() default "storageId";
 
     String repositoryVariableName() default "repositoryId";
+
+    boolean allowOutOfServiceRepository() default false;
```
Comment (carlspring) [inline strongbox-web-core/src/main/java/org/carlspring/strongbox/web/RepositoryMapping.java]: What exactly does this mean? I seem to be misunderstanding something... It should be possible to have a repository that is out of service. What does "allow out of service" mean?

File: strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/configuration/StoragesConfigurationController.java (hunk 8 above)
Comment (anki2189) [reply strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/configuration/StoragesConfigurationController.java]: Done.

File: strongbox-web-core/src/main/java/org/carlspring/strongbox/web/RepositoryMapping.java (hunk 9 above)
Comment (anki2189) [reply strongbox-web-core/src/main/java/org/carlspring/strongbox/web/RepositoryMapping.java]: @carlspring There are two use cases(end points) of Repository . One is `/api/configuration/**` used to manage Repository/Storage Configuration and another one is `/storages/**` used mainly in various layouts.
We should allow to add/update/delete operation on `Out of Storage` Repository, to handle such scenario, `allowOutOfServiceRepository` is introduced.

Comment (steve-todorov) [reply strongbox-web-core/src/main/java/org/carlspring/strongbox/web/RepositoryMapping.java]: This annotation is used in controllers which handle `storage administration`. In those cases you don't case about the status of the repository since you are administrating it.

Comment (carlspring) [reply strongbox-web-core/src/main/java/org/carlspring/strongbox/web/RepositoryMapping.java]: It should always be possible to update/configure repositories, regardless of whether or not they are in service. Hence my asking of why we need this sort of field in he first place. I, personally, don't see the need for it. Perhaps, I'm misunderstanding your explanation...?

Comment (steve-todorov) [reply strongbox-web-core/src/main/java/org/carlspring/strongbox/web/RepositoryMapping.java]: You should probably check out the code. The annotation was created as part of #528 and used to convert `/{storageId}/{repositoryId}` into a `Repository` object. If the `repository` is "out of service" the argument resolver will return a `ServiceUnavailableException`. However, this behavior is also being triggered for `updating/configuring` repositories since the annotation is used there as well which is why `allowOutOfServiceRepository=true` is needed.

Comment (carlspring) [reply strongbox-web-core/src/main/java/org/carlspring/strongbox/web/RepositoryMapping.java]: Thanks for the explanation! :)

File: strongbox-web-core/src/test/java/org/carlspring/strongbox/web/RepositoryMethodArgumentResolverTest.java [hunk 10]
```diff
@@ -0,0 +1,331 @@
...
+import org.springframework.web.context.request.ServletWebRequest;
+import org.springframework.web.method.support.ModelAndViewContainer;
+import org.springframework.web.servlet.HandlerMapping;
+
+/**
+ * @author ankit.tomar
+ */
+@SpringBootTest
+@ContextConfiguration(classes = RepositoryMethodArgumentResolverTest.RepositoryMethodArgumentResolverConfiguration.class)
+@ActiveProfiles({ "test", "RepositoryMethodArgumentResolverTest" })
```
Comment (sbespalov) [inline strongbox-web-core/src/test/java/org/carlspring/strongbox/web/RepositoryMethodArgumentResolverTest.java]: we probably should have `SINGLE_THREAD` execution here.

Comment (anki2189) [reply strongbox-web-core/src/test/java/org/carlspring/strongbox/web/RepositoryMethodArgumentResolverTest.java]: Fixed.

Comment (anki2189) [reply strongbox-web-core/src/test/java/org/carlspring/strongbox/web/RepositoryMethodArgumentResolverTest.java]: @sbespalov : You are suggesting Single thread execution because Test case is using Mocked instances of `NativeWebRequest`, `WebDataBinderFactory`... , right?

Comment (sbespalov) [reply strongbox-web-core/src/test/java/org/carlspring/strongbox/web/RepositoryMethodArgumentResolverTest.java]: yes

Comment (anki2189) [reply strongbox-web-core/src/test/java/org/carlspring/strongbox/web/RepositoryMethodArgumentResolverTest.java]: Thanks. :)

Comment (sbespalov) [reply strongbox-web-core/src/test/java/org/carlspring/strongbox/web/RepositoryMethodArgumentResolverTest.java]: you're always welcome :)

**Comment by steve-todorov** [comment]
Thanks for the review guys and thanks @anki2189 for your work on this! :)

**Comment by gretel** [comment]
many thanks!
