### PR TITLE
Issue 1048: Fix the deprecation warnings in the strongbox-default-authentication-provider module

### LINKED ISSUE #1048: Fix the deprecation warnings in the strongbox-default-authentication-provider module
# Task Description

The `strongbox-default-authentication-provider` module uses or overrides a deprecated API and this will have to be investigated and fixed.

```
22:13:25  [INFO] /home/jenkins/workspace/jenkins-strongbox-strongbox-master-2034-pQSJhpa/strongbox-security/strongbox-authentication-providers/strongbox-default-authentication-provider/src/main/java/org/carlspring/strongbox/authentication/api/impl/xml/CacheManagerAuthenticationCache.java: /home/jenkins/workspace/jenkins-strongbox-strongbox-master-2034-pQSJhpa/strongbox-security/strongbox-authentication-providers/strongbox-default-authentication-provider/src/main/java/org/carlspring/strongbox/authentication/api/impl/xml/CacheManagerAuthenticationCache.java uses or overrides a deprecated API.
22:13:25  [INFO] /home/jenkins/workspace/jenkins-strongbox-strongbox-master-2034-pQSJhpa/strongbox-security/strongbox-authentication-providers/strongbox-default-authentication-provider/src/main/java/org/carlspring/strongbox/authentication/api/impl/xml/CacheManagerAuthenticationCache.java: Recompile with -Xlint:deprecation for details.
```

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

### PR DESCRIPTION
**Pull request by adavid9**
Fixes #1048.

### CODE REVIEW

**Comment by carlspring** [comment]
Wow! Thanks for the quick fix!

File: strongbox-security/strongbox-authentication-providers/strongbox-default-authentication-provider/src/main/java/org/carlspring/strongbox/authentication/api/impl/xml/CacheManagerAuthenticationCache.java [hunk 1]
```diff
@@ -3,11 +3,11 @@
 import org.carlspring.strongbox.data.CacheName;
 import org.springframework.cache.annotation.Cacheable;
 import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
-import org.springframework.security.crypto.password.StandardPasswordEncoder;
+import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
 
 public class CacheManagerAuthenticationCache implements AuthenticationCache
 {
-    private StandardPasswordEncoder standardPasswordEncoder = new StandardPasswordEncoder();
```
Comment (fuss86) [inline strongbox-security/strongbox-authentication-providers/strongbox-default-authentication-provider/src/main/java/org/carlspring/strongbox/authentication/api/impl/xml/CacheManagerAuthenticationCache.java]: we used `StandardPasswordEncoder` because it's faster than `BCryptPasswordEncoder`. We were aware it's not safe to use `SHA-256`. Maybe we should consider `@SuppressWarnings` here. 

@sbespalov what do you think ?

Comment (carlspring) [reply strongbox-security/strongbox-authentication-providers/strongbox-default-authentication-provider/src/main/java/org/carlspring/strongbox/authentication/api/impl/xml/CacheManagerAuthenticationCache.java]: +1: You're right, @fuss86! I remember we had some performance issues with bcrypt!

@sbespalov : I think it was you who implemented the workaround...?

Could you please remind me what the issue was and how we sorted it out?

Also, could you give @adavid9 some hints on how to improve his pull request?

Comment (sbespalov) [reply strongbox-security/strongbox-authentication-providers/strongbox-default-authentication-provider/src/main/java/org/carlspring/strongbox/authentication/api/impl/xml/CacheManagerAuthenticationCache.java]: we shouldn't drop `StandardPasswordEncoder`, this should be just muted with `@SuppressWarnings`  as Przemyslaw suggested.

**Comment by adavid9** [comment]
@carlspring this fix is ready to merge.
