### PR TITLE
Issue-1475: Test that ArtifactEntity properties created, lastUpdated, lastUsed retain time when saved and read to/from db

### LINKED ISSUE #1475: OrientDb stores java.util.Date without time
# Bug Description

As described in the subject, `orientDb` stores `java.util.Date` without time. For example, once stored `org.carlspring.strongbox.domain.ArtifactEntry#created` is always at midnight.

# Steps To Reproduce

1. Run `org.carlspring.strongbox.services.impl.ArtifactEntryServiceTest` and watch the logs

# Expected Behavior

`org.carlspring.strongbox.domain.ArtifactEntry#created` and other `java.util.Date` fields should be stored in database with proper time

### PR DESCRIPTION
**Pull request by evsikov**
# Pull Request Description

Adds tests for ArtifactEntry properties that used to have a type of 'date' but now should have a type of 'datetime' and thus store not only date, but also retain time information.

This pull request closes #1475.

# Acceptance Test

* [X] Building the code with `mvn clean install -Dintegration.tests` still works.
* [X] Running `mvn spring-boot:run` in the `strongbox-web-core` still starts up the application correctly.
* [x] Building the code and running the `strongbox-distribution` from a `zip` or `tar.gz` still works.
* [x] The tests in the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) still run properly.

# Questions

* Does this pull request break backward compatibility? 
  * [ ] Yes
  * [X] No

* Does this pull request require other pull requests to be merged first? 
  * [X] Yes, please see:
https://github.com/strongbox/strongbox-db/pull/16

  * [ ] No

* Does this require an update of the documentation?
  * [ ] Yes, please see strongbox/strongbox-docs#{PR_NUMBER}
  * [X] No

### CODE REVIEW

**Comment by sbespalov** [comment]
@evsikov thanks for the PR!

One thing I would like to clarify. You made this custom `o:changePropertyTypeDateToDatetime` Liquibase command, what OrientDB statements it will produce?

The another question is that probably it will be better to split this custom command into something more generic, few other commands like for example drop property with one command and then create new property with another command.

**Comment by fuss86** [comment]
Good job @evsikov :)

I agree with @sbespalov - it would be best if it can be more generic - what do you think, it is possible ? I have some doubts though, since there are `.asDateTime()` and `.asDate()` functions used, but maybe you can try using some design patterns ? We can support `date` to `datetime` migration at the beginning :)

**Comment by evsikov** [comment]
@sbespalov , the decision to have single liquibase command for that was made, because it is a very specific situation when normal 'ALTER ArtifactEntity.created TYPE datetime' does not work. Instead I have a workaround that is being used since many years by orientdb users.
Statements, that are generated by this command, can be found here:
https://github.com/strongbox/liquibase-orientdb/blob/79878e5a49dd2edfda6d11baade3ac223354c76d/src/main/java/liquibase/change/ext/ChangePropertyTypeDateToDatetimeChange.java
I will break it into several statements now.

**Comment by evsikov** [comment]
@fuss86, these '.asDatetime()' and '.asDate()' are actually orientDb SQLMethods. There are much more of them. So far they haven't been required. Not until now. And since it is not a common case, I don't see the reason to complicate things right now. But if you want me to implement something that you think would look cool here, please give me some details, I will code it. :-)

File: strongbox-storage/strongbox-storage-api/src/test/java/org/carlspring/strongbox/services/impl/ArtifactEntryServiceTest.java [hunk 1]
```diff
@@ -362,6 +364,80 @@ public void searchByTwoCoordinate(TestInfo testInfo)
...
+
+        final ArtifactEntry secondTimeReadFromDatabase = artifactEntryService.findOne(artifactEntryId)
+                .orElse(null);
+
+        assertThat(secondTimeReadFromDatabase).isNotNull();
+        assertThat(secondTimeReadFromDatabase.getCreated()).isEqualTo(creationDate);
+    }
+
+    @Test
+    public void saveEntityCreatedLastUsedLastUpdatedPropertiesShouldRetainTime(TestInfo testInfo) throws ParseException {
```
Comment (carlspring) [inline strongbox-storage/strongbox-storage-api/src/test/java/org/carlspring/strongbox/services/impl/ArtifactEntryServiceTest.java]: Cosmetic: Braces and `throws` clause on new lines, please! Thanks! :)

File: strongbox-storage/strongbox-storage-api/src/test/java/org/carlspring/strongbox/services/impl/ArtifactEntryServiceTest.java [hunk 2]
```diff
@@ -362,6 +364,80 @@ public void searchByTwoCoordinate(TestInfo testInfo)
...
+                .orElse(null);
+
+        assertThat(firstTimeReadFromDatabase).isNotNull();
+        assertThat(firstTimeReadFromDatabase.getCreated()).isEqualTo(creationDate);
+
+        artifactEntry.setDownloadCount(1);
+        save(firstTimeReadFromDatabase);
+
+        final ArtifactEntry secondTimeReadFromDatabase = artifactEntryService.findOne(artifactEntryId)
+                .orElse(null);
```
Comment (carlspring) [inline strongbox-storage/strongbox-storage-api/src/test/java/org/carlspring/strongbox/services/impl/ArtifactEntryServiceTest.java]: Cosmetic: Could you please align the chained method calls like this:
```
        final ArtifactEntry secondTimeReadFromDatabase = artifactEntryService.findOne(artifactEntryId)
                                                                             .orElse(null);
 ```

Could you please change this in all other places across the pull request as well? Thanks! :)

**Comment by fuss86** [comment]
@sbespalov here are the statements (taking `ArtifactEntry.lastUsed` as an example):

```
DROP PROPERTY ArtifactEntry.lastUsed
UPDATE ArtifactEntry SET ArtifactEntry.lastUsedb7f253f1_c6ee_49e0_b9ae_edc0b887fa6a = ArtifactEntry.lastUsed.asDateTime()
UPDATE ArtifactEntry REMOVE ArtifactEntry.lastUsed
UPDATE ArtifactEntry SET ArtifactEntry.lastUsed = ArtifactEntry.lastUsedb7f253f1_c6ee_49e0_b9ae_edc0b887fa6a
UPDATE ArtifactEntry REMOVE ArtifactEntry.lastUsedb7f253f1_c6ee_49e0_b9ae_edc0b887fa6a
CREATE PROPERTY ArtifactEntry.lastUsed DATETIME
```

I think we should comment on this https://github.com/strongbox/liquibase-orientdb/pull/2/files PR

**Comment by fuss86** [comment]
@evsikov I left comments here https://github.com/strongbox/liquibase-orientdb/pull/2 and here https://github.com/strongbox/strongbox-db/pull/16

In order to make this PR pass in Jenkins couple of things need to be done:
* we need to deploy https://github.com/strongbox/liquibase-orientdb/pull/2 into strongbox nexus (@steve-todorov , help needed :) ) - see also https://repo.carlspring.org/content/groups/carlspring/org/unbroken-dome/liquibase-orientdb/liquibase-orientdb/
* once above point is done and related artifact is hosted in strongbox nexus, you need to change `strongbox-parent` version and used `liquibase-orientdb` (I saw you've already started it in https://github.com/strongbox/strongbox-parent/pull/43, so parent version needs to be changed following convention: https://repo.carlspring.org/content/groups/carlspring/org/carlspring/strongbox/strongbox-parent/)
* then you need to change `strongbox-parent` version in https://github.com/strongbox/strongbox-db/pull/16 (`strongbox-db` version should be changed too) to match your PR. This version should be hosted in strongbox nexus as well (@steve-todorov  help needed :) )
* finally this PR https://github.com/strongbox/strongbox/pull/1504 needs to have updated  `strongbox-parent` version and `strongbox-db` version.

File: strongbox-storage/strongbox-storage-api/src/test/java/org/carlspring/strongbox/services/impl/ArtifactEntryServiceTest.java (hunk 1 above)
Comment (evsikov) [reply strongbox-storage/strongbox-storage-api/src/test/java/org/carlspring/strongbox/services/impl/ArtifactEntryServiceTest.java]: Done

File: strongbox-storage/strongbox-storage-api/src/test/java/org/carlspring/strongbox/services/impl/ArtifactEntryServiceTest.java (hunk 2 above)
Comment (evsikov) [reply strongbox-storage/strongbox-storage-api/src/test/java/org/carlspring/strongbox/services/impl/ArtifactEntryServiceTest.java]: Done

**Comment by evsikov** [comment]
> @evsikov I left comments here [strongbox/liquibase-orientdb#2](https://github.com/strongbox/liquibase-orientdb/pull/2) and here [strongbox/strongbox-db#16](https://github.com/strongbox/strongbox-db/pull/16)
> 
> In order to make this PR pass in Jenkins couple of things need to be done:
> 
> * we need to deploy [strongbox/liquibase-orientdb#2](https://github.com/strongbox/liquibase-orientdb/pull/2) into strongbox nexus (@steve-todorov , help needed :) ) - see also https://repo.carlspring.org/content/groups/carlspring/org/unbroken-dome/liquibase-orientdb/liquibase-orientdb/
> * once above point is done and related artifact is hosted in strongbox nexus, you need to change `strongbox-parent` version and used `liquibase-orientdb` (I saw you've already started it in [strongbox/strongbox-parent#43](https://github.com/strongbox/strongbox-parent/pull/43), so parent version needs to be changed following convention: https://repo.carlspring.org/content/groups/carlspring/org/carlspring/strongbox/strongbox-parent/)
> * then you need to change `strongbox-parent` version in [strongbox/strongbox-db#16](https://github.com/strongbox/strongbox-db/pull/16) (`strongbox-db` version should be changed too) to match your PR. This version should be hosted in strongbox nexus as well (@steve-todorov  help needed :) )
> * finally this PR #1504 needs to have updated  `strongbox-parent` version and `strongbox-db` version.

Thank you for all the work, I owe you an apology. Because of my poor understanding of OrientDb I overcomplicated the issue. Finally I realized that everything is much easier and we need only 2 PR's out of 4.

**Comment by fuss86** [comment]
> 
> 
> > @evsikov I left comments here [strongbox/liquibase-orientdb#2](https://github.com/strongbox/liquibase-orientdb/pull/2) and here [strongbox/strongbox-db#16](https://github.com/strongbox/strongbox-db/pull/16)
> > In order to make this PR pass in Jenkins couple of things need to be done:
> > 
> > * we need to deploy [strongbox/liquibase-orientdb#2](https://github.com/strongbox/liquibase-orientdb/pull/2) into strongbox nexus (@steve-todorov , help needed :) ) - see also https://repo.carlspring.org/content/groups/carlspring/org/unbroken-dome/liquibase-orientdb/liquibase-orientdb/
> > * once above point is done and related artifact is hosted in strongbox nexus, you need to change `strongbox-parent` version and used `liquibase-orientdb` (I saw you've already started it in [strongbox/strongbox-parent#43](https://github.com/strongbox/strongbox-parent/pull/43), so parent version needs to be changed following convention: https://repo.carlspring.org/content/groups/carlspring/org/carlspring/strongbox/strongbox-parent/)
> > * then you need to change `strongbox-parent` version in [strongbox/strongbox-db#16](https://github.com/strongbox/strongbox-db/pull/16) (`strongbox-db` version should be changed too) to match your PR. This version should be hosted in strongbox nexus as well (@steve-todorov  help needed :) )
> > * finally this PR #1504 needs to have updated  `strongbox-parent` version and `strongbox-db` version.
> 
> Thank you for all the work, I owe you an apology. Because of my poor understanding of OrientDb I overcomplicated the issue. Finally I realized that everything is much easier and we need only 2 PR's out of 4.
> Now there's only one PR to be closed before this one.
> 
>     1. [strongbox/strongbox-db#16](https://github.com/strongbox/strongbox-db/pull/16)

Will it update previous values ?

**Comment by evsikov** [comment]
@fuss86, yes, it retains data
1. DROP PROPERTY ArtifactEntry.created; (drops schema type 'created' only, data is not deleted)
2. CREATE PROPERTY ArtifactEntry.created datetime; (Uses existing 'created' values as a data for new schema property)

**Comment by sbespalov** [comment]
@evsikov it seems we have same problem with [UserEntry](https://github.com/strongbox/strongbox/blob/master/strongbox-security/strongbox-user-management/src/main/java/org/carlspring/strongbox/domain/UserEntry.java#L30). Would be great if you can provide another PR for it.

**Comment by carlspring** [comment]
@sbespalov ,

Would you mind raising a new issue for this? Thanks! :)

**Comment by carlspring** [comment]
@evsikov ,

Thank you for your contributiion and congratulations on your first pull request!

@fuss86 , @sbespalov .

Thanks for reviewing! :)
