### PR TITLE
Issue 1789: Repositories generated using the @MavenRepository do not set the basedir variable (against issue-1649)

### LINKED ISSUE #1789: Repositories generated using the @MavenRepository do not set the basedir variable
# Bug Description

When using the `@MavenRepository` (and most-likely the other similar test annotations for NPM, Nuget, PyPi, etc) does not set a value for the `basedir`, which then makes it impossible to get the path to the base directory of the repository.

# Steps To Reproduce

Given:
```java
@ActiveProfiles(profiles = "test")
@SpringBootTest
public class MavenRepositoryAnnotationTest
{

    private static final String REPOSITORY_RELEASES_REMOTE = "releases-remote";

    @ExtendWith({ RepositoryManagementTestExecutionListener.class,
                  ArtifactManagementTestExecutionListener.class })
    @Test
    public void testIncrementalUpdate(@MavenRepository(repositoryId = REPOSITORY_RELEASES_REMOTE)
                                      Repository repositoryRemote)
    {
        ...
    }
```
You should be able to do:
```java
    String repositoryBaseDir = repository.getBasedir();
```

However, this currently returns `null`.

# Expected Behavior

This should return the correct path to the repository's base directory.

# Tasks

* [ ] Investigate and fix this for the `@MavenRepository` annotation, along with a test case.
* [ ] Investigate and fix this for the `@NpmRepository` annotation, along with a test case.
* [ ] Investigate and fix this for the `@NugetRepository` annotation, along with a test case.
* [ ] Investigate and fix this for the `@PypiRepository` annotation, along with a test case.
* [ ] Investigate and fix this for the `@RpmRepository` annotation, along with a test case.
* [ ] Investigate and fix this for the `@RawRepository` annotation, along with a test case.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov

### PR DESCRIPTION
**Pull request by anki2189**
# Pull Request Description

This pull request closes #1789 

# Acceptance Test

* [x] Building the code with `mvn clean install -Dintegration.tests` still works.
* [x] Running `mvn spring-boot:run` in the `strongbox-web-core` still starts up the application correctly.
* [x] Building the code and running the `strongbox-distribution` from a `zip` or `tar.gz` still works.
* [x] The tests in the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) still run properly.

# Questions

* Does this pull request break backward compatibility? 
  * [ ] Yes
  * [x] No

* Does this pull request require other pull requests to be merged first? 
  * [ ] Yes, please see #...
  * [x] No

* Does this require an update of the documentation?
  * [ ] Yes, please see strongbox/strongbox-docs#{PR_NUMBER}
  * [x] No

### CODE REVIEW

File: strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/testing/repository/MavenRepositoryManagementTest.java [hunk 1]
```diff
@@ -0,0 +1,59 @@
...
+ * @author ankit.tomar
+ */
+@SpringBootTest
+@ActiveProfiles(profiles = "test")
+@ContextConfiguration(classes = Maven2LayoutProviderTestConfig.class)
+@Execution(ExecutionMode.CONCURRENT)
+public class MavenRepositoryManagementTest
+{
+
+    private static final String MAVEN_STORAGE = "maven-storage-to-be-injected";
```
Comment (carlspring) [inline strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/testing/repository/MavenRepositoryManagementTest.java:28]: Our convention is to use the initials of the test's name. In this case, it should be `mrmt-storage` and `mrmt-releases`.

File: strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/testing/repository/MavenRepositoryManagementTest.java [hunk 2]
```diff
@@ -0,0 +1,59 @@
...
+
+    private static final String MAVEN_REPOSITORY = "maven-repository-to-be-injected";
+
+    @ExtendWith({ RepositoryManagementTestExecutionListener.class })
+    @Test
+    public void testValidRepositoryShouldBeInjected(@MavenRepository(repositoryId = MAVEN_REPOSITORY,
+                                                                     storageId = MAVEN_STORAGE)
```
Comment (carlspring) [inline strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/java/org/carlspring/strongbox/testing/repository/MavenRepositoryManagementTest.java:35]: Cosmetic: Could you please swap the places of the `storageId` and `repositoryId` parameters? (Logically, first comes the storage and then the repositories are inside of it). Thanks! :)

File: strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-npm-layout-provider/src/test/java/org/carlspring/strongbox/testing/repository/NpmRepositoryManagementTest.java [hunk 3]
```diff
@@ -0,0 +1,59 @@
...
+{
+
+    private static final String NPM_STORAGE = "npm-storage-to-be-injected";
+
+    private static final String NPM_REPOSITORY = "npm-repository-to-be-injected";
+
+    @ExtendWith({ RepositoryManagementTestExecutionListener.class })
+    @Test
+    public void testValidRepositoryShouldBeInjected(@NpmRepository(repositoryId = NPM_REPOSITORY,
+                                                                   storageId = NPM_STORAGE)
```
Comment (carlspring) [inline strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-npm-layout-provider/src/test/java/org/carlspring/strongbox/testing/repository/NpmRepositoryManagementTest.java:35]: Cosmetic: Please, swap as above.

File: strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-npm-layout-provider/src/test/java/org/carlspring/strongbox/testing/repository/NpmRepositoryManagementTest.java [hunk 4]
```diff
@@ -0,0 +1,59 @@
...
+@SpringBootTest
+@ActiveProfiles(profiles = "test")
+@ContextConfiguration(classes = NpmLayoutProviderTestConfig.class)
+@Execution(ExecutionMode.CONCURRENT)
+public class NpmRepositoryManagementTest
+{
+
+    private static final String NPM_STORAGE = "npm-storage-to-be-injected";
+
+    private static final String NPM_REPOSITORY = "npm-repository-to-be-injected";
```
Comment (carlspring) [inline strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-npm-layout-provider/src/test/java/org/carlspring/strongbox/testing/repository/NpmRepositoryManagementTest.java:30]: Cosmetic: Could you please use the convention I mentioned above? Thanks! :)

File: strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/test/java/org/carlspring/strongbox/testing/repository/NugetRepositoryManagementTest.java [hunk 5]
```diff
@@ -0,0 +1,59 @@
...
+@SpringBootTest
+@ActiveProfiles(profiles = "test")
+@ContextConfiguration(classes = NugetLayoutProviderTestConfig.class)
+@Execution(ExecutionMode.CONCURRENT)
+public class NugetRepositoryManagementTest
+{
+
+    private static final String NUGET_STORAGE = "nuget-storage-to-be-injected";
+
+    private static final String NUGET_REPOSITORY = "nuget-repository-to-be-injected";
```
Comment (carlspring) [inline strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/test/java/org/carlspring/strongbox/testing/repository/NugetRepositoryManagementTest.java:30]: As above.

File: strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/test/java/org/carlspring/strongbox/testing/repository/NugetRepositoryManagementTest.java [hunk 6]
```diff
@@ -0,0 +1,59 @@
...
+
+    @ExtendWith({ RepositoryManagementTestExecutionListener.class })
+    @Test
+    public void testValidRepositoryShouldBeInjected(@NugetRepository(repositoryId = NUGET_REPOSITORY,
+                                                                     storageId = NUGET_STORAGE)
```
Comment (carlspring) [inline strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/test/java/org/carlspring/strongbox/testing/repository/NugetRepositoryManagementTest.java:35]: As above.

File: strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-pypi-layout-provider/src/test/java/org/carlspring/strongbox/testing/repository/PypiRepositoryManagementTest.java [hunk 7]
```diff
@@ -0,0 +1,58 @@
...
+ */
+@SpringBootTest
+@ActiveProfiles(profiles = "test")
+@Execution(CONCURRENT)
+@ContextConfiguration(classes = PypiLayoutProviderTestConfig.class)
+public class PypiRepositoryManagementTest
+{
+    private static final String PYPI_STORAGE = "pypi-storage-to-be-injected";
+
+    private static final String PYPI_REPOSITORY = "pypi-repository-to-be-injected";
```
Comment (carlspring) [inline strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-pypi-layout-provider/src/test/java/org/carlspring/strongbox/testing/repository/PypiRepositoryManagementTest.java:29]: As above.

File: strongbox-storage/strongbox-storage-api/src/test/java/org/carlspring/strongbox/testing/repository/RawRepositoryManagementTest.java [hunk 8]
```diff
@@ -0,0 +1,59 @@
...
+@SpringBootTest
+@ActiveProfiles(profiles = "test")
+@ContextConfiguration(classes = StorageApiTestConfig.class)
+@Execution(ExecutionMode.CONCURRENT)
+public class RawRepositoryManagementTest
+{
+
+    private static final String RAW_STORAGE = "raw-storage-to-be-injected";
+
+    private static final String RAW_REPOSITORY = "rwa-repository-to-be-injected";
```
Comment (carlspring) [inline strongbox-storage/strongbox-storage-api/src/test/java/org/carlspring/strongbox/testing/repository/RawRepositoryManagementTest.java:30]: Our convention is to use the initials of the test's name. In this case, it should be `rrmt-storage` and `rrmt-releases`.

File: strongbox-storage/strongbox-storage-api/src/test/java/org/carlspring/strongbox/testing/repository/RawRepositoryManagementTest.java [hunk 9]
```diff
@@ -0,0 +1,59 @@
...
+
+    @ExtendWith({ RepositoryManagementTestExecutionListener.class })
+    @Test
+    public void testValidRepositoryShouldBeInjected(@NullRepository(repositoryId = RAW_REPOSITORY,
+                                                                    storageId = RAW_STORAGE)
```
Comment (carlspring) [inline strongbox-storage/strongbox-storage-api/src/test/java/org/carlspring/strongbox/testing/repository/RawRepositoryManagementTest.java:35]: Cosmetic: Could you please swap the places of the `storageId` and `repositoryId` parameters? (Logically, first comes the storage and then the repositories are inside of it). Thanks! :)
