### PR TITLE
Issue-528: HandlerMethodArgumentResolver to resolve Repository instance based on `{storageId}/{repositoryId}` path variables

### LINKED ISSUE #528: HandlerMethodArgumentResolver to resolve Repository instance based on `{storageId}/{repositoryId}` path variables
We'd like to have a Controller request method argument resolver for `org.carlspring.strongbox.storage.repository.Repository` instances.

For example, consider existing `org.carlspring.strongbox.controllers.TrashController#undelete` method which looks like this:

```
@RequestMapping(value = "{storageId}/{repositoryId}/{path:.+}", method = RequestMethod.POST)
public ResponseEntity undelete(@PathVariable String storageId, @PathVariable String repositoryId, @PathVariable String path)
```
In many Controllers we have repeated pre-conditions validating existence of the repository for provided path variables. 

It'd be awesome if we could refactor above implementation to something like:

```
@RequestMapping(value = "{storageId}/{repositoryId}/{path:.+}", method = RequestMethod.POST)
public ResponseEntity undelete(@RepositoryMapping Repository repository, @PathVariable String path)
```

Implemented `HandlerMethodArgumentResolver` should validate:
* Repository existence (followed by storage existence check first, of course)
* If repository `Repository.isInService().`

If validation fails, we should throw some newly implemented Exception(s) and handle it/them using `@ControllerAdvice`/`@ExceptionHandler` spring features.

### PR DESCRIPTION
**Pull request by ptirador**
Fixes #528.

Created a resolver which:

- Checks if exists a method parameter annotation `RepositoryMapping` with a parameter type `Repository`.
- If there's no `storageId` nor `repositoryId` path variables, a `MissingPathVariableException` is thrown.
- Validates the existence of an storage and a repository. Otherwise an `ElementNotFoundException` is thrown.
- Validates if repository is in service. Otherwise a `ServiceUnavailableException` is thrown.

# Tasks

* [x] Modify all affected controller methods with path variables `{storageId}/{repositoryId}`, and replace the parameters with new annotation `RepositoryMapping`.

# Acceptance Test

* [x] Building the code with `mvn clean install -Dintegration.tests` still works.
* [x] Running `mvn spring-boot:run` in the `strongbox-web-core` still starts up the application correctly.
* [x] Building the code and running the `strongbox-distribution` from a `zip` or `tar.gz` still works.
* [x] The tests in the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) still run properly.

### CODE REVIEW

**Comment by ptirador** [comment]
@carlspring This is ready for review. Any suggestions are welcome.

**Comment by carlspring** [comment]
@fuss86 , @sbespalov ,

Could you please review this pull request?

**Comment by fuss86** [comment]
@ptirador thank you for your hard work, but it needs to wait for https://github.com/strongbox/strongbox/pull/1272

**Comment by carlspring** [comment]
@ptirador ,

Could you please rebase? Thanks! :)

@fuss86 ,

Is it good to go after the rebase?

**Comment by carlspring** [comment]
@sbespalov ,

Will this pull request be affected by #1293?

**Comment by carlspring** [comment]
I forgot to mention that #1272 has been merged.

**Comment by ptirador** [comment]
> @ptirador ,
> 
> Could you please rebase? Thanks! :)
> 
> @fuss86 ,
> 
> Is it good to go after the rebase?

Rebase done.

**Comment by carlspring** [comment]
Thanks, @ptirador :)

File: strongbox-web-core/src/main/java/org/carlspring/strongbox/web/RepositoryMapping.java [hunk 1]
```diff
@@ -0,0 +1,29 @@
...
+@Retention(RUNTIME)
+@Target(PARAMETER)
+public @interface RepositoryMapping
+{
+
+    String value() default "";
+
+    String name() default "";
+
+    boolean required() default true;
```
Comment (fuss86) [inline strongbox-web-core/src/main/java/org/carlspring/strongbox/web/RepositoryMapping.java]: `required` I think you should use/validate this attribute in the `RepositoryInstanceMethodArgumentResolver`

File: strongbox-web-core/src/main/java/org/carlspring/strongbox/web/RepositoryMapping.java [hunk 2]
```diff
@@ -0,0 +1,29 @@
...
+
+    boolean validateRepository() default true;
```
Comment (fuss86) [inline strongbox-web-core/src/main/java/org/carlspring/strongbox/web/RepositoryMapping.java]: `validateRepository` is not used or I am missing something ?

File: strongbox-web-core/src/main/java/org/carlspring/strongbox/web/RepositoryInstanceMethodArgumentResolver.java [hunk 3]
```diff
@@ -0,0 +1,126 @@
...
+    }
+
+    @Override
+    public Object resolveArgument(final MethodParameter parameter,
+                                  final ModelAndViewContainer modelAndViewContainer,
+                                  final NativeWebRequest nativeWebRequest,
+                                  final WebDataBinderFactory webDataBinderFactory)
+            throws MissingPathVariableException
+    {
+        final String storageId = validateAndGetPathVariable(parameter, nativeWebRequest, "storageId");
```
Comment (fuss86) [inline strongbox-web-core/src/main/java/org/carlspring/strongbox/web/RepositoryInstanceMethodArgumentResolver.java]: Could you please try to receive the `Repository ` from request attribute ? See `org.carlspring.strongbox.web.RepositoryRequestCondition#expose`. If there isn't then you should use the logic you actually perform here, Thanks

File: strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/configuration/HttpConnectionPoolConfigurationManagementController.java [hunk 4]
```diff
@@ -48,34 +48,24 @@ public HttpConnectionPoolConfigurationManagementController(ConfigurationManageme
...
-        {
-            return ResponseEntity.status(HttpStatus.NOT_FOUND)
-                                 .body(getResponseEntityBody("The repository does not exist!", accept));
-        }
+        final ImmutableRepository immutableRepository = (ImmutableRepository) repository;
+        final String storageId = immutableRepository.getStorage().getId();
+        final String repositoryId = immutableRepository.getId();
 
-        if (((ImmutableRepository)repository).getRemoteRepository() == null)
+        if (immutableRepository.getRemoteRepository() == null)
```
[the remark this answers is not in the document]
Comment (sbespalov) [reply strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/configuration/HttpConnectionPoolConfigurationManagementController.java]: :+1: 
But this probably should be a separate task.

File: strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/configuration/HttpConnectionPoolConfigurationManagementController.java [hunk 5]
```diff
@@ -48,34 +48,24 @@ public HttpConnectionPoolConfigurationManagementController(ConfigurationManageme
...
             return ResponseEntity.status(HttpStatus.BAD_REQUEST)
                                  .body(getResponseEntityBody("The proxy repository has no associated remote repository.", accept));
         }
 
         configurationManagementService.setProxyRepositoryMaxConnections(storageId, repositoryId, numberOfConnections);
-        proxyRepositoryConnectionPoolConfigurationService.setMaxPerRepository(repository.getRemoteRepository().getUrl(),
-                                                                              numberOfConnections);
+        proxyRepositoryConnectionPoolConfigurationService.setMaxPerRepository(
+                immutableRepository.getRemoteRepository().getUrl(),
+                numberOfConnections);
```
Comment (sbespalov) [inline strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/configuration/HttpConnectionPoolConfigurationManagementController.java]: @carlspring we should finally decide something with common formatting style we all should use.

I prefer how it was before this change.

File: strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/layout/nuget/NugetArtifactController.java [hunk 6]
```diff
@@ -56,28 +26,43 @@
...
-import org.springframework.web.bind.annotation.GetMapping;
-import org.springframework.web.bind.annotation.PathVariable;
-import org.springframework.web.bind.annotation.RequestHeader;
-import org.springframework.web.bind.annotation.RequestMapping;
-import org.springframework.web.bind.annotation.RequestMethod;
-import org.springframework.web.bind.annotation.RequestParam;
-import org.springframework.web.bind.annotation.RestController;
+import org.springframework.web.bind.annotation.*;
 import org.springframework.web.context.request.RequestContextHolder;
 import org.springframework.web.context.request.ServletRequestAttributes;
```
Comment (sbespalov) [inline strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/layout/nuget/NugetArtifactController.java]: @carlspring same thing with imports, it's possible to have common import optimization configuration for all.

File: strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/layout/nuget/NugetArtifactController.java [hunk 7]
```diff
@@ -194,7 +184,7 @@ public ResponseEntity deletePackage(@RequestHeader(name = "X-NuGet-ApiKey", requ
 
         PackageFeed feed = transform(feedId, files);
 
-        response.setHeader("content-type", MediaType.APPLICATION_XML);
+        response.setHeader(HttpHeaders.CONTENT_TYPE, MediaType.APPLICATION_XML);
```
Comment (sbespalov) [inline strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/layout/nuget/NugetArtifactController.java]: :+1:

File: strongbox-web-core/src/main/java/org/carlspring/strongbox/validation/ElementNotFoundException.java [hunk 8]
```diff
@@ -0,0 +1,40 @@
+package org.carlspring.strongbox.validation;
+
+import org.apache.commons.lang3.StringUtils;
+
+/**
+ * @author Pablo Tirado
+ */
+public class ElementNotFoundException
```
[the remark this answers is not in the document]
Comment (sbespalov) [reply strongbox-web-core/src/main/java/org/carlspring/strongbox/validation/ElementNotFoundException.java]: @ptirador I also suggest to have `RepositoryNotFound` and `StorageNotFound` instead of one `ElementNotFound`

File: strongbox-web-core/src/main/java/org/carlspring/strongbox/validation/ElementNotFoundException.java [hunk 9]
```diff
@@ -0,0 +1,40 @@
...
+        super(cause);
+    }
+
+    public ElementNotFoundException(final String message,
+                                    final Throwable cause,
+                                    final boolean enableSuppression,
+                                    final boolean writableStackTrace)
+    {
+        super(message, cause, enableSuppression, writableStackTrace);
+    }
```
Comment (sbespalov) [inline strongbox-web-core/src/main/java/org/carlspring/strongbox/validation/ElementNotFoundException.java]: @ptirador can you please leave just constructors that actually used?

File: strongbox-web-core/src/main/java/org/carlspring/strongbox/web/RepositoryInstanceMethodArgumentResolver.java [hunk 10]
```diff
@@ -0,0 +1,126 @@
...
+import org.springframework.web.context.request.NativeWebRequest;
+import org.springframework.web.context.request.RequestAttributes;
+import org.springframework.web.method.support.HandlerMethodArgumentResolver;
+import org.springframework.web.method.support.ModelAndViewContainer;
+import org.springframework.web.servlet.HandlerMapping;
+
+/**
+ * @author Pablo Tirado
+ */
+public class RepositoryInstanceMethodArgumentResolver
```
Comment (sbespalov) [inline strongbox-web-core/src/main/java/org/carlspring/strongbox/web/RepositoryInstanceMethodArgumentResolver.java]: this probably better to be named just `RepositoryMethodArgumentResolver`

File: strongbox-web-core/src/main/java/org/carlspring/strongbox/web/RepositoryInstanceMethodArgumentResolver.java (hunk 3 above)
Comment (sbespalov) [reply strongbox-web-core/src/main/java/org/carlspring/strongbox/web/RepositoryInstanceMethodArgumentResolver.java]: there is also `REPOSITORY_NOT_FOUND_REQUEST_ATTRIBUTE` and `STORAGE_NOT_FOUND_REQUEST_ATTRIBUTE`.

File: strongbox-web-core/src/main/java/org/carlspring/strongbox/web/RepositoryMapping.java [hunk 11]
```diff
@@ -0,0 +1,29 @@
...
+ */
+@Documented
+@Retention(RUNTIME)
+@Target(PARAMETER)
+public @interface RepositoryMapping
+{
+
+    String value() default "";
+
+    String name() default "";
```
Comment (sbespalov) [inline strongbox-web-core/src/main/java/org/carlspring/strongbox/web/RepositoryMapping.java]: @ptirador I think we better have `repositoryVariableName` and `storageVariableName` attributes here, with default values `storageId` and `repositoryId`, and use it within `HandlerMethodArgumentResolver`, instead of `name` and `value` (which seems never used).

File: strongbox-web-core/src/main/java/org/carlspring/strongbox/web/RepositoryInstanceMethodArgumentResolver.java (hunk 3 above)
Comment (sbespalov) [reply strongbox-web-core/src/main/java/org/carlspring/strongbox/web/RepositoryInstanceMethodArgumentResolver.java]: @ptirador also you should check that `storageId` and `repositoryId` match with that you have in request attributes.

**Comment by ptirador** [comment]
Thanks so much for your tips, @fuss86 and @sbespalov!
I've fixed almost everything that you said, except for two things:
1. This [discussion](https://github.com/strongbox/strongbox/pull/1290#discussion_r287879888) about the need of casting the `Repository` class, which should be in a follow-up task. CC @carlspring

2.This [discussion](https://github.com/strongbox/strongbox/pull/1290#discussion_r287882975) about receiving the `Repository` class from `request` atribute. I'm not very sure how to implement this, could you help me?

Thanks.

File: strongbox-web-core/src/main/java/org/carlspring/strongbox/web/RepositoryMethodArgumentResolver.java [hunk 12]
```diff
@@ -0,0 +1,130 @@
...
+    public Object resolveArgument(final MethodParameter parameter,
+                                  final ModelAndViewContainer modelAndViewContainer,
+                                  final NativeWebRequest nativeWebRequest,
+                                  final WebDataBinderFactory webDataBinderFactory)
+            throws MissingPathVariableException
+    {
+        final RepositoryMapping repositoryMapping = parameter.getParameterAnnotation(RepositoryMapping.class);
+        final String storageVariableName = repositoryMapping.storageVariableName();
+        final String storageId = validateAndGetPathVariable(parameter, nativeWebRequest, storageVariableName);
+
```
Comment (sbespalov) [inline strongbox-web-core/src/main/java/org/carlspring/strongbox/web/RepositoryMethodArgumentResolver.java]: @ptirador you can check `Repository` from request like below:
```
Repository repository = nativeWebRequest.getNativeRequest(HttpServletRequest.class).getAttribute( 
org.carlspring.strongbox.web.Constants.REPOSITORY_REQUEST_ATTRIBUTE);
if (repository != null && repository.getId().equeals(repositoryId) && repository.getStorage().getId().equals(storageId)){
    return repository;
}
```

File: strongbox-web-core/src/main/java/org/carlspring/strongbox/config/WebConfig.java [hunk 13]
```diff
@@ -271,4 +273,16 @@ MavenArtifactRequestInterceptor mavenArtifactRequestInterceptor(RepositoryPathRe
...
     }
+
+    @Override
+    public void addArgumentResolvers(List<HandlerMethodArgumentResolver> argumentResolvers)
+    {
+        argumentResolvers.add(repositoryInstanceMethodArgumentResolver());
+    }
+
+    @Bean
+    public RepositoryMethodArgumentResolver repositoryInstanceMethodArgumentResolver()
```
Comment (fuss86) [inline strongbox-web-core/src/main/java/org/carlspring/strongbox/config/WebConfig.java]: `repositoryInstanceMethodArgumentResolver` it should be renamed to match `RepositoryMethodArgumentResolver `

File: strongbox-web-core/src/main/java/org/carlspring/strongbox/web/RepositoryMapping.java [hunk 14]
```diff
@@ -0,0 +1,25 @@
...
+ *
+ * @author Pablo Tiraoo
+ */
+@Documented
+@Retention(RUNTIME)
+@Target(PARAMETER)
+public @interface RepositoryMapping
+{
+
+    String storageVariableName() default "storageId";
```
Comment (fuss86) [inline strongbox-web-core/src/main/java/org/carlspring/strongbox/web/RepositoryMapping.java]: Thanks to this change you probably can use this approach in the `MavenArtifactController#copy` twice, for `srcRepository` and for `destRepository`

File: strongbox-web-core/src/main/java/org/carlspring/strongbox/web/RepositoryMethodArgumentResolver.java [hunk 15]
```diff
@@ -0,0 +1,142 @@
...
+        if (!inService)
+        {
+            final String message = String.format(NOT_IN_SERVICE_REPOSITORY_MESSAGE, storageId, repositoryId);
+            throw new ServiceUnavailableException(message);
+        }
+
+        return repository;
+    }
+
+    private String validateAndGetPathVariable(final MethodParameter parameter,
```
Comment (fuss86) [inline strongbox-web-core/src/main/java/org/carlspring/strongbox/web/RepositoryMethodArgumentResolver.java]: `getRequiredPathVariable` sounds better here in my opinion than `validateAndGetPathVariable`

**Comment by ptirador** [comment]
@fuss86: changes fixed!

**Comment by ptirador** [comment]
@carlspring: if there's no more review requests, this would be ready.

File: strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/configuration/HttpConnectionPoolConfigurationManagementController.java (hunk 4 above)
[the remark this answers is not in the document]
Comment (carlspring) [reply strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/configuration/HttpConnectionPoolConfigurationManagementController.java]: @sbespalov : I've restored the previous formatting.

File: strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/configuration/HttpConnectionPoolConfigurationManagementController.java (hunk 5 above)
Comment (carlspring) [reply strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/configuration/HttpConnectionPoolConfigurationManagementController.java]: @sbespalov : I've restored the previous formatting.

**Comment by carlspring** [comment]
@fuss86 / @sbespalov ,

Do you have other remarks, or should I proceed with merging it?

**Comment by carlspring** [comment]
Thanks, @ptirador !
