### PR TITLE
Issue-956: Fix the JWT test issues in the SpringSecurityTest

### LINKED ISSUE #956: Fix the JWT test issues in the SpringSecurityTest
Tests methods to be re-written in the `SpringSecurityTest`:
* [ ] `testJWTAuth()`
* [ ] `testJWTExpire()`

### PR DESCRIPTION
**Pull request by adavid9**
Fixes #956

### CODE REVIEW

**Comment by steve-todorov** [comment]
LGTM. @sbespalov any additional notes? :)

File: strongbox-web-core/src/test/java/org/carlspring/strongbox/controllers/JwtAuthenticationTest.java [hunk 1]
```diff
@@ -0,0 +1,120 @@
...
+                             .get(getContextBaseUrl() + "/login")
+                             .then()
+                             .statusCode(HttpStatus.OK.value())
+                             .extract()
+                             .asString();
+
+        // this token will expire after 1 hour
+        String tokenValue = getTokenValue(body);
+
+        given().header(HttpHeaders.AUTHORIZATION, tokenValue)
```
Comment (sbespalov) [inline strongbox-web-core/src/test/java/org/carlspring/strongbox/controllers/JwtAuthenticationTest.java]: the authentication header in this case actually should be `Authorization: Bearer {token}`, it's strange that it passes with just `{token}`.
@adavid9 can you please check it?

File: strongbox-web-core/src/test/java/org/carlspring/strongbox/controllers/JwtAuthenticationTest.java [hunk 2]
```diff
@@ -0,0 +1,120 @@
...
+
+        Thread.sleep(1500);
+
+        given().header(HttpHeaders.AUTHORIZATION, expiredToken)
+               .header(HttpHeaders.ACCEPT, MediaType.APPLICATION_JSON_VALUE)
+               .when()
+               .get(url)
+               .then()
+               .statusCode(HttpStatus.UNAUTHORIZED.value())
+               .body("error", equalTo(UNAUTHORIZED_MESSAGE));
```
Comment (sbespalov) [inline strongbox-web-core/src/test/java/org/carlspring/strongbox/controllers/JwtAuthenticationTest.java]: In case of expired token it should return `expired` message like assumed [here](https://github.com/strongbox/strongbox/blob/master/strongbox-security/strongbox-authentication-providers/strongbox-default-authentication-provider/src/main/java/org/carlspring/strongbox/authentication/api/impl/xml/JwtAuthenticationProvider.java#L52). 

@adavid9 can you please also check it?

File: strongbox-web-core/src/test/java/org/carlspring/strongbox/controllers/JwtAuthenticationTest.java [hunk 3]
```diff
@@ -0,0 +1,120 @@
...
+    @WithAnonymousUser
+    public void testJWTExpirationToken()
+            throws Exception
+    {
+
+        String url = getContextBaseUrl() + "/users";
+
+        // generate token that will expire after 1 second
+        String expiredToken = securityTokenProvider.getToken("admin", Collections.emptyMap(), 1);
+
```
Comment (sbespalov) [inline strongbox-web-core/src/test/java/org/carlspring/strongbox/controllers/JwtAuthenticationTest.java]: it also need to be checked that token not expired at the beginning and expired only when expected time passed.

File: strongbox-web-core/src/test/java/org/carlspring/strongbox/controllers/JwtAuthenticationTest.java (hunk 1 above)
Comment (sbespalov) [reply strongbox-web-core/src/test/java/org/carlspring/strongbox/controllers/JwtAuthenticationTest.java]: should be resolved with [commit](https://github.com/strongbox/strongbox/pull/1073/commits/1d3062dc6eee6738cc76b1eddd9dd5802427792d)

**Comment by sbespalov** [comment]
@carlspring this ready to be merged

@adavid9 thanks for your work

**Comment by carlspring** [comment]
Thanks for reviewing, @sbespalov and thanks for your help, @adavid9 ! :)
